      SUBROUTINE ADDZCG(ZCG,LREF,FORCE,MOMENT)
C
C***  CHANGE PITCHING MOMENT COEFFICIENT OR ROLLING MOMENT
C***  COEFFICENT DUE TO A CHANGE IN THE VERTICAL CENTER OF
C***  GRAVITY LOCATION.  ZCG IS POSITIVE UP.
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      REAL LREF,MOMENT
C
      IF(FORCE.EQ.UNUSED .OR. MOMENT.EQ.UNUSED)GO TO 1000
C
      MOMENT=MOMENT-FORCE*ZCG/LREF
C
 1000 CONTINUE
C
      RETURN
      END
