      SUBROUTINE BDCMV(ALPHA,CDC,ETA,SPLAN,XCG,XCENTP,SREF,
     1   LREF,CMVIS)
C
C***  SUBROUTINE TO COMPUTE THE VISCOUS PITCHING MOMENT FOR BODIES
C***  ABOUT THE USER SPECIFIED CENTER OF GRAVITY
C***  METHOD OF ALLEN AND PERKINS
C
C***  INPUTS
C
C  ALPHA -- ANGLE OF ATTACK, DEGREES
C    CDC -- CROSS FLOW DRAG COEFFICIENT
C    ETA -- CROSS FLOW DRAG PROPORTIONALITY FACTOR
C  SPLAN -- PLANFORM AREA, FEET SQUARED
C    XCG -- LOCATION OF LONGITUDINAL CENTER OF GRAVITY, FEET FROM NOSE
C XCENTP -- LOCATION OF PLANFORM AREA CENTROID OF BODY, FEET FROM NOSE
C   SREF -- REFERENCE AREA, FEET SQUARED
C   LREF -- REFERENCE LENGTH, FEET
C
C***  OUTPUT
C
C  CMVIS -- VISCOUS PITCHING MOMENT COEFFICIENT
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      REAL LREF
C
      SINALP=SIN(ALPHA/RAD)
      CMVIS=CDC*ETA*SPLAN*(XCG-XCENTP)/LREF*SINALP*ABS(SINALP)/SREF
C
      RETURN
      END
