      SUBROUTINE BDCNP(CNALP,ALPHA,CNP)
C
C***  SUBROUTINE TO COMPUTE THE POTENTIAL NORMAL FORCE FOR BODIES
C***  METHOD OF ALLEN AND PERKINS
C
C  MODIFIED BY W. BLAKE, WL/FIGC
C
C***  INPUTS
C
C  CNALP -- POTENTIAL NORMAL FORCE SLOPE, PER RADIAN
C  ALPHA -- ANGLE OF ATTACK, DEGREES
C
C***  OUTPUT
C
C    CNP -- POTENTIAL NORMAL FORCE COEFFICIENT AT ALPHA
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
C  REV 1/96 CORRECT CALCULATION FOR ALPHA > 90 OR < -90
C
      ALP=ABS(ALPHA)
      IF(ALP.GT.90.) ALP=180.-ALP
      CNP=CNALP/2.*SIN(2.*ALP/RAD)*COS(ALP/RAD/2.)
      IF(ALPHA.LT.0.) CNP=-CNP
C
      RETURN
      END
