      SUBROUTINE BDCNV(ALPHA,CDC,ETA,SPLAN,SREF,CNVIS)
C
C***  SUBROUTINE TO COMPUTE THE VISCOUS NORMAL FORCE FOR BODIES
C***  METHOD OF ALLEN AND PERKINS
C
C***  INPUTS
C
C  ALPHA -- ANGLE OF ATTACK, DEGREES
C    CDC -- CROSS FLOW DRAG COEFFICIENT
C    ETA -- CROSS FLOW DRAG PROPORTIONALITY FACTOR
C  SPLAN -- PLANFORM AREA, FEET SQUARED
C   SREF -- REFERENCE AREA, FEET SQUARED
C
C***  OUTPUT
C
C  CNVIS -- VISCOUS NORMAL FORCE COEFFICIENT AT ALPHA
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      SINALP=SIN(ALPHA/RAD)
      CNVIS=CDC*ETA*SPLAN*SINALP*ABS(SINALP)/SREF
C
      RETURN
      END
