      SUBROUTINE BDXCPB(LTOTAL,LAFT,VOLAFT,DAFT,SMAX,XCPB)
C
C***  SUBROUTINE TO LOCATE THE AFT BODY CENTER OF PRESSURE
C***  SLENDER-BODY THEORY METHOD (REFERENCE NSWC-TR-80-346, P.41)
C
C***  INPUTS
C
C LTOTAL -- OVERALL BODY LENGTH, FEET
C   LAFT -- AFT BODY LENGTH, FEET
C VOLAFT -- AFT BODY VOLUME, FEET CUBED
C   DAFT -- BASE DIAMETER OF AFTERBODY, FEET
C   SMAX -- MAXIMUM CROSS SECTIONAL AREA OF AFTERBODY, FEET SQUARED
C
C***  OUTPUT
C
C   XCPB -- AFT CENTER OF PRESSURE FROM BODY NOSE, CALIBERS
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      REAL LTOTAL,LAFT
C
      DREF=SQRT(4.*SMAX/PI)
C
      XCPB=LTOTAL/DREF
C
      IF(DREF .EQ. DAFT)GO TO 1000
C
      XCPB=XCPB-(LAFT*SMAX-VOLAFT)/(DREF*(SMAX-PI*DAFT**2/4.))
C
 1000 CONTINUE
C
      RETURN
      END
