      SUBROUTINE CAFRIC(ALPHA,MACH,REN,LTOTAL,ROUGH,BLAYER,SWET,
     1 SREF,LAM3D,TUR3D,CAF)
C
C***  SUBROUTINE TO COMPUTE THE FRICTION COMPONENT OF AXIAL FORCE
C***  AT ANGLE OF ATTACK
C
C***  INPUTS
C
C  ALPHA -- ANGLE OF ATTACK, DEGREES
C   MACH -- MACH NUMBER
C    REN -- REYNOLDS NUMBER PER FOOT OF LENGTH (FREESTREAM)
C LTOTAL -- CHARACTERISTIC LENGTH
C  ROUGH -- SURFACE ROUGHNESS HEIGHT, INCHES
C BLAYER -- BOUNDARY LAYER TYPE
C           0.=TURBULENT, 1.=MIXED LAMINAR/TURBULENT
C   SWET -- WETTED SURFACE AREA, FEET SQUARED
C   SREF -- REFERENCE AREA, FEET SQUARED
C  LAM3D -- 3-DIMENSIONAL CORRECTION FACTOR FOR LAMINAR FLOW
C  TUR3D -- 3-DIMENSIONAL CORRECTION FACTOR FOR TURBULENT FLOW
C
C***  OUTPUT
C
C    CAF -- AXIAL FORCE CONTRIBUTION DUE TO FRICTION
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      REAL MACH,LTOTAL,LAM3D
C
C***    SET CROSS FLOW MACH NUMBER AND REYNOLDS NUMBER
C
C  REV 1/96 UPDATE   USE ABS(COS(ALP)) INSTEAD OF COS(ABS(ALP))
C
        AMACHC=MACH*ABS(COS(ALPHA/RAD))
        RENC=REN*ABS(COS(ALPHA/RAD))
C
C     * IF THE AXIAL FLOW MACH NUMBER OR REYNOLDS NUMBER IS NOT ZERO
           IF(AMACHC .NE. 0. .AND. RENC .NE. 0.)GO TO 1000
           GO TO 1010
C       THEN COMPUTE THE SKIN FRICTION COEFFICIENT
 1000      CALL SKINF(AMACHC,RENC,LTOTAL,ROUGH,BLAYER,SWET,SREF,1.,
     1       LAM3D,TUR3D,CAF)
           GO TO 1020
C       ELSE SET IT TO ZERO
 1010      CAF=0.0
 1020      CONTINUE
C     * ENDIF
C
      RETURN
      END
