      SUBROUTINE CHKEND(KOL,KAND,END)
C
C***  SUBROUTINE TO CHECK IF LAST NAMELIST COMPLETE
C
      COMMON /PARTF/ PARTS(19)
      LOGICAL PARTS
      DIMENSION KOL(80)
      LOGICAL END
      CHARACTER*4 IBLANK,KAND,KOL
      DATA IBLANK / '    ' /
C
      IF(KOL(2).EQ.KAND.AND.(.NOT.END).AND.PARTS(17))
     1 WRITE(6,1000)KAND
      IF(KOL(2).EQ.KAND.AND.(.NOT.END))WRITE(8,1010)KAND,(IBLANK,
     1 J=1,75)
      IF(KOL(2).EQ.KAND.AND.(.NOT.END))END=.TRUE.
 1000 FORMAT(2X,A1,'END',8X,'** MISSING NAMELIST TERMINATION',
     1 ' ADDED **')
 1010 FORMAT(1X,A1,'END',75A1)
      RETURN
      END
