      SUBROUTINE CONEP(GAM,AM,SD,PC)
C
C  COMPUTE CONE PRESSURE AT ZERO ANGLE OF ATTACK FROM THE METHOD
C  OF RASMUSSEN (AIAA JOURNAL, AUGUST 1967, PAGE 1495)
C
C  INPUTS
C
C    GAM -- RATIO OF SPECIFIC HEATS FOR THE GAS (1.4 FOR AIR)
C     AM -- FREE STREAM MACH NUMBER
C     SD -- SINE OF THE SEMI-APEX ANGLE
C
C  OUTPUT
C
C     PC -- PRESSURE ON THE SURFACE
C
C  SUBROUTINES CALLED -- NONE
C
      IF(SD.LT.0.005)GO TO 1000
         AKS=(AM**2-1.)*SD**2
         T=ALOG((GAM+1.)/2.+1./AKS)
         CP=SD**2*(1.+((GAM+1.)*AKS+2.)*T/((GAM-1.)*AKS+2.))
      GO TO 1010
 1000 CP=0.
 1010 PC=1.0+GAM/2.*AM**2*CP
      RETURN
      END
