      SUBROUTINE CPDIST(SALP,CALP,LAMDA,GAMMA,DELTA,CP,CPP)
C
C  COMPUTE THE PRESSURES AROUND THE BODY
C  USE EQUATION 28 OF DEJARNETTE
C  REFERENCE - DEJARNETTE (AIAA J. SPACECRAFT, NOV-DEC 1980, P.529)
C
C  INPUTS
C
C   SALP -- SINE OF THE ANGLE OF ATTACK
C   CALP -- COSINE OF THE ANGLE OF ATTACK
C  LAMDA -- D (P)/D(ALPHA)  AT PHI=ALPHA=0
C  GAMMA -- D2(P)/D(ALPHA)2 AT PHI=ALPHA=0
C  DELTA -- D2(P)/D(ALPHA)2 AT PHI=90. DEG, ALPHA=0
C     CP -- PRESSURE COEFFICIENT AT ZERO ANGLE OF ATTACK
C
C  OUTPUTS
C
C    CPP -- ARRAY OF PRESSURES ABOUT THE BODY AT THIS STATION
C
C  SUBROUTINES CALLED -- NONE
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      REAL LAMDA
      DIMENSION CPP(7)
      DO 1000 K=1,7
         XK=7-K
         PHI=XK*PI/6.0
         CPH=COS(PHI)
         CP2=CPH**2
         T1=LAMDA*CPH*SALP*CALP*2.0
         T2=(GAMMA*CP2+DELTA*(1.0-CP2))
         CPP(K)=CP+T1+T2*SALP**2/2.0
 1000 CONTINUE
      RETURN
      END
