      SUBROUTINE CVRBOD(ISIGN)
C
C***  ROUTINE TO CONVERT THE DATA IN THE BODY ALONE
C***  DATA BLOCKS BETWEEN THE USER AND FOOT SYSTEM OF UNITS
C
      COMMON /ABODIN/ NX,XO,X(50),R(50),TNOSE,LNOSE,DNOSE,BNOSE,TRUNC,
     1                LCENTR,DCENTR,TAFT,LAFT,DAFT,POWER,DISCON(20),
     2                ELLIP(50),H(50),ENOSE,ECENTR,EAFT,DEXIT,
     3                BASE,BETAN,JMACH(20),PRAT(20),TRAT(20),
     4                PROTUB,NPROT,PTYPE(20),XPROT(20),NLOC(20),
     5                BLDMEM(20),BLDTYP(100),LPROT(100),WPROT(100),
     6                HPROT(100),OPROT(100)
      COMMON /GEOBOD/ SPNOSE,SWNOSE,VOLNOS,XCVNOS,XCPNOS,FRNOSE,
     1  THEOLN,THEOFN,SPCENT,SWCENT,VOLCEN,XCVCEN,XCPCEN,FRCENT,
     2  THEOLC,THEOFC,SPAFT ,SWAFT ,VOLAFT,XCVAFT,XCPAFT,FRAFT ,
     3  THEOLA,THEOFA,SPLAN ,SWET  ,VOL   ,XCENTV,XCENTP,FR    ,
     4                DBASE ,SBASE ,DMAX  ,SMAX  ,LTOTAL,
     5  BPNOSE,BCPNOS,BPCENT,BCPCEN,BPAFT,BCPAFT,BPLAN,
     6  BCENTP,ECSPN,ECSPC,ECSPA,ECSPT
C
      REAL    NX,LNOSE,LCENTR,LAFT,LTOTAL,NPROT,NLOC,LPROT,JMACH
      LOGICAL TRUNC,BASE,PROTUB
      COMMON /INLETN/ NIN,INTYPE,XINLT,XDIV,HDIV,LDIV,PHIROL(20),
     1                XI(5),HI(5),WI(5),ICOVER,RAMANG,IAD,MFR(20)
      REAL NIN,INTYPE,LDIV
      LOGICAL ICOVER
C
C      
C***  CONVERT BODY INPUTS
C
      CALL CONVRT(XO,1,ISIGN*1)
      CALL CONVRT(X,50,ISIGN*1)
      CALL CONVRT(R,50,ISIGN*1)
      CALL CONVRT(LNOSE,1,ISIGN*1)
      CALL CONVRT(DNOSE,1,ISIGN*1)
      CALL CONVRT(BNOSE,1,ISIGN*1)
      CALL CONVRT(LCENTR,1,ISIGN*1)
      CALL CONVRT(DCENTR,1,ISIGN*1)
      CALL CONVRT(LAFT,1,ISIGN*1)
      CALL CONVRT(DAFT,1,ISIGN*1)
      CALL CONVRT(H,50,ISIGN*1)
      CALL CONVRT(DEXIT,1,ISIGN*1)
      CALL CONVRT(XPROT,20,ISIGN*1)
      CALL CONVRT(LPROT,100,ISIGN*1)
      CALL CONVRT(WPROT,100,ISIGN*1)
      CALL CONVRT(HPROT,100,ISIGN*1)
      CALL CONVRT(OPROT,100,ISIGN*1)
C
C***  CONVERT INLET INPUTS
C
      CALL CONVRT(XINLT,1,ISIGN*1)
      CALL CONVRT(XI,5,ISIGN*1)
      CALL CONVRT(HI,5,ISIGN*1)
      CALL CONVRT(WI,5,ISIGN*1)
C
C***  CONVERT DIVERTER INPUTS
C
      CALL CONVRT(XDIV,1,ISIGN*1)
      CALL CONVRT(HDIV,1,ISIGN*1)
      CALL CONVRT(LDIV,1,ISIGN*1)
C
C
C***  CONVERT CALCULATED BODY DATA
C
      CALL CONVRT(SPNOSE,1,ISIGN*2)
      CALL CONVRT(SWNOSE,1,ISIGN*2)
      CALL CONVRT(VOLNOS,1,ISIGN*3)
      CALL CONVRT(XCVNOS,1,ISIGN*1)
      CALL CONVRT(XCPNOS,1,ISIGN*1)
      CALL CONVRT(THEOLN,1,ISIGN*1)
      CALL CONVRT(SPCENT,1,ISIGN*2)
      CALL CONVRT(SWCENT,1,ISIGN*2)
      CALL CONVRT(VOLCEN,1,ISIGN*3)
      CALL CONVRT(XCVCEN,1,ISIGN*1)
      CALL CONVRT(XCPCEN,1,ISIGN*1)
      CALL CONVRT(THEOLC,1,ISIGN*1)
      CALL CONVRT(SPAFT ,1,ISIGN*2)
      CALL CONVRT(SWAFT ,1,ISIGN*2)
      CALL CONVRT(VOLAFT,1,ISIGN*3)
      CALL CONVRT(XCVAFT,1,ISIGN*1)
      CALL CONVRT(XCPAFT,1,ISIGN*1)
      CALL CONVRT(THEOLA,1,ISIGN*1)
      CALL CONVRT(SPLAN ,1,ISIGN*2)
      CALL CONVRT(SWET  ,1,ISIGN*2)
      CALL CONVRT(VOL   ,1,ISIGN*3)
      CALL CONVRT(XCENTV,1,ISIGN*1)
      CALL CONVRT(XCENTP,1,ISIGN*1)
      CALL CONVRT(DBASE,1,ISIGN*1)
      CALL CONVRT(SBASE,1,ISIGN*2)
      CALL CONVRT(DMAX,1,ISIGN*1)
      CALL CONVRT(SMAX,1,ISIGN*2)
      CALL CONVRT(LTOTAL,1,ISIGN*1)
      CALL CONVRT(BPNOSE,1,ISIGN*2)
      CALL CONVRT(BCPNOS,1,ISIGN*1)
      CALL CONVRT(BPCENT,1,ISIGN*2)
      CALL CONVRT(BCPCEN,1,ISIGN*1)
      CALL CONVRT(BPAFT,1,ISIGN*2)
      CALL CONVRT(BCPAFT,1,ISIGN*1)
      CALL CONVRT(BPLAN,1,ISIGN*2)
      CALL CONVRT(BCENTP,1,ISIGN*1)
      CALL CONVRT(ECSPN,1,ISIGN*1)
      CALL CONVRT(ECSPC,1,ISIGN*1)
      CALL CONVRT(ECSPA,1,ISIGN*1)
      CALL CONVRT(ECSPT,1,ISIGN*1)
C
      RETURN
      END
