      SUBROUTINE CVRREF(ISIGN)
C
C***  ROUTINE TO CONVERT THE DATA IN THE REFERENCE QUANTITIES
C***  DATA BLOCKS BETWEEN THE USER AND FOOT SYSTEM OF UNITS
C
      COMMON /REFQN/  SREF,LREF,LATREF,ROUGH,XCG,ZCG,SCALE,BLAYER,RHR
      REAL LREF,LATREF
C
C***  CONVERT REFERENCE QUANTITIES
C
      CALL CONVRT(SREF,1,ISIGN*2)
      CALL CONVRT(LREF,1,ISIGN*1)
      CALL CONVRT(LATREF,1,ISIGN*1)
      CALL CONVRT(XCG,1,ISIGN*1)
      CALL CONVRT(ZCG,1,ISIGN*1)
C
      RETURN
      END
