      FUNCTION DSWET(NPTS,X,R)
C
C**  FUNCTION TO INTEGRATE FOR WETTED AREA
C
C***  INPUTS
C
C   NPTS -- NUMBER OF INPUT POINTS
C      X -- X STATIONS
C      R -- RADII AT EACH X STATION
C
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      DIMENSION X(NPTS),R(NPTS)
C
      DSWET=0.0
      DO 1000 I=2,NPTS
         DX=X(I)-X(I-1)
         DR=R(I)-R(I-1)
         DSWET=DSWET+PI*(R(I)+R(I-1))*SQRT(DX**2+DR**2)
 1000 CONTINUE
      RETURN
      END
