      SUBROUTINE FDP5(TX,TY,X,Y,N,J)
C
C     THIS SUBROUTINE IS USED IN CONJUNCTION WITH FD5 TO DETERMINE
C     A DERIVATIVE AT A GIVEN POINT WHICH IS BETWEEN THE INPUT POINTS.
C
C  WRITTEN BY F. MOORE, NSWC
C
      DIMENSION TX(50),TY(50)
      IF((N-J).EQ.1)GO TO 1010
      I=J-1
      K=J+2
 1000 I=I+1
      IF(TX(I).LT.X) GO TO 1000
      IF(I.LE.K) I=K
      IF(I.GT.(N-2)) I=N-2
      CALL FD5(X,TX(I-2),TX(I-1),TX(I),TX(I+1),TX(I+2),TY(I-2),TY(I-1
     1),TY(I),TY(I+1),TY(I+2),Y)
      GO TO 1020
 1010 Y=(TY(N)-TY(J))/(TX(N)-TX(J))
 1020 CONTINUE
      RETURN
      END
