      SUBROUTINE FPART9(IM,NSET,NALP,ALPHA,XCPL,XCPNL,XCG,LREF,
     1 CML,CMNL,CM,XO,CNA,CNL,CNNL,CN)
C
C***  FORTRAN 90 VERSION
C***  PRINT FIN SET PARTIAL OUTPUT FOR NORMAL FORCE
C***  AND PITCHING MOMENT
C
      DIMENSION ALPHA(20),CML(20),CMNL(20),CM(20)
      DIMENSION CNL(20),CNNL(20),CN(20)
C
      REAL LREF
C
      LOGICAL NA,NM,ND
C
      DXCPL=((XCG-XO)-XCPL)/LREF
      DXCPNL=((XCG-XO)-XCPNL)/LREF
C
      CALL HEADR9
      WRITE(6,1010)NSET
      CALL PRFLC9(IM,NA,NM,ND)
      WRITE(6,1020) CNA,DXCPL,DXCPNL
C
      WRITE(6,1030)
C
      DO 1000 I=1,NALP
         WRITE(6,1040) ALPHA(I),CNL(I),CNNL(I),CN(I),
     1                 CML(I),CMNL(I),CM(I)
 1000 CONTINUE
C
 1010 FORMAT(23X,'FIN SET',I2,' CN, CM PARTIAL OUTPUT',/)
 1020 FORMAT(4X,'NORMAL FORCE SLOPE AT ALPHA ZERO, CNA =',F11.5,
     1          '/DEG (1 PANEL)',/,
     2       4X,'     CENTER OF PRESSURE FOR LINEAR CN =',F11.5,
     3          ' (CALIBERS FROM C.G.)',/,
     4       4X,' CENTER OF PRESSURE FOR NON-LINEAR CN =',F11.5,
     5          ' (CALIBERS FROM C.G.)',/)
 1030 FORMAT(4X,2X,'ALPHA',6X,'CN',8X,'CN',8X,'CN',8X,'CM',
     2  8X,'CM',8X,'CM',/,15X,'LINEAR',2X,'NON-LINEAR',2X,'TOTAL',
     3  5X,'LINEAR',2X,'NON-LINEAR',2X,'TOTAL',/)
 1040 FORMAT(4X,F7.2,6F10.4)
C
      RETURN
      END
