      SUBROUTINE GEOM
C
C***  TOP LEVEL EXECUTIVE ROUTINE FOR CALCULATING GEOMETRIC DATA
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
      COMMON /LOGIC/ LDMPCS,LDAMP,LBUILD,LNACA,LDERDG,
     1               LDERRD,LPART,LNAME,LPLOT,
     2               LFLT,LREFQ,LAXIS,LFIN1,LFIN2,LFIN3,LFIN4,
     3               LDEFL,LTRIM,LDIMIN,LDIMFT,LDIMCM,LDIMM,LELLB,
     4               LINLET,LEXPR,LICRMT,LSPIN,LARBOD
      LOGICAL        LDMPCS,LDAMP,LBUILD,LNACA,LDERDG,
     1               LDERRD,LPART,LNAME,LPLOT,
     2               LFLT,LREFQ,LAXIS,LFIN1,LFIN2,LFIN3,LFIN4,
     3               LDEFL,LTRIM,LDIMIN,LDIMFT,LDIMCM,LDIMM,LELLB,
     4               LINLET,LEXPR,LICRMT,LSPIN,LARBOD
C
      COMMON /ABODIN/ NX,XO,X(50),R(50),TNOSE,LNOSE,DNOSE,BNOSE,
     1                TRUNC,LCENTR,DCENTR,TAFT,LAFT,DAFT,POWER,
     2                DISCON(20),ELLIP(50),H(50),ADUM(648)
      REAL NX,LNOSE,LCENTR,LAFT,LREF,LATREF
      LOGICAL TRUNC
C
      COMMON /REFQN/  SREF,LREF,LATREF,ROUGH,XCG,ZCG,SCALE,BLAYER,RHR
C
      COMMON /FSET1/  FDATA1(399)
      COMMON /FSET2/  FDATA2(399)
      COMMON /FSET3/  FDATA3(399)
      COMMON /FSET4/  FDATA4(399)
C
C***  SCALE REFERENCE QUANTITIES IF REQUIRED
C
      IF(SREF.NE.UNUSED .AND. SCALE.GT.UNUSED)SREF=SREF*SCALE**2
      IF(LREF.NE.UNUSED .AND. SCALE.GT.UNUSED)LREF=LREF*SCALE
      IF(LATREF.NE.UNUSED .AND. SCALE.GT.UNUSED)LATREF=LATREF*SCALE
      IF(XCG .NE. UNUSED .AND. SCALE .GT. UNUSED)XCG=XCG*SCALE
      IF(ZCG .NE. UNUSED .AND. SCALE .GT. UNUSED)ZCG=ZCG*SCALE
C
C***  CONVERT ALL USER INPUTS TO FEET-POUNDS-DEGREES RANKINE
C
      CALL CVRTUS
C
C***  COMPUTE AXISYMMETRIC BODY DATA
C
      IF(LAXIS .AND. .NOT.LELLB)CALL GEOAXI
C
C***  COMPUTE ELLIPTICAL BODY DATA
C
      IF(LELLB)CALL GEOELL
C
C***  COMPUTE FIN ALONE GEOMETRY DATA
C
      IF(LFIN1.OR.LFIN2.OR.LFIN3.OR.LFIN4)CALL GEOFIN
C
C***  PUT FIN ON BODY SURFACE IF SSPAN(1) EQUALS ZERO
C
      IF(.NOT.(LAXIS .OR. LELLB))GO TO 1080
C
      NNX=NX+.5
C
      IF(FDATA1(2) .NE. 0.)GO TO 1020
C
      XCRO2=FDATA1(102)+FDATA1(52)/2.
C
      IF(XCRO2 .LT. X(1) .OR. XCRO2 .GT. X(NNX))GO TO 1020
C
      CALL LNTRP(X,R,NNX,XCRO2,RCRO2)
      IF(LELLB)CALL LNTRP(X,H,NNX,XCRO2,HCRO2)
      IF(LELLB)RCRO2=RCRO2*HCRO2/SQRT(RCRO2**2+HCRO2**2)
C
      DO 1010 I=1,10
         IF(FDATA1(I+1) .NE. UNUSED)FDATA1(I+1)=FDATA1(I+1)+RCRO2
 1010 CONTINUE
C
 1020 IF(FDATA2(2) .NE. 0.)GO TO 1040
C
      XCRO2=FDATA2(102)+FDATA2(52)/2.
C
      IF(XCRO2 .LT. X(1) .OR. XCRO2 .GT. X(NNX))GO TO 1040
C
      CALL LNTRP(X,R,NNX,XCRO2,RCRO2)
      IF(LELLB)CALL LNTRP(X,H,NNX,XCRO2,HCRO2)
      IF(LELLB)RCRO2=RCRO2*HCRO2/SQRT(RCRO2**2+HCRO2**2)
C
      DO 1030 I=1,10
         IF(FDATA2(I+1) .NE. UNUSED)FDATA2(I+1)=FDATA2(I+1)+RCRO2
 1030 CONTINUE
C
 1040 IF(FDATA3(2) .NE. 0.)GO TO 1060
C
      XCRO2=FDATA3(102)+FDATA3(52)/2.
C
      IF(XCRO2 .LT. X(1) .OR. XCRO2 .GT. X(NNX))GO TO 1060
C
      CALL LNTRP(X,R,NNX,XCRO2,RCRO2)
      IF(LELLB)CALL LNTRP(X,H,NNX,XCRO2,HCRO2)
      IF(LELLB)RCRO2=RCRO2*HCRO2/SQRT(RCRO2**2+HCRO2**2)
C
      DO 1050 I=1,10
         IF(FDATA3(I+1) .NE. UNUSED)FDATA3(I+1)=FDATA3(I+1)+RCRO2
 1050 CONTINUE
C
 1060 IF(FDATA3(2) .NE. 0.)GO TO 1080
C
      XCRO2=FDATA3(102)+FDATA3(52)/2.
C
      IF(XCRO2 .LT. X(1) .OR. XCRO2 .GT. X(NNX))GO TO 1080
C
      CALL LNTRP(X,R,NNX,XCRO2,RCRO2)
      IF(LELLB)CALL LNTRP(X,H,NNX,XCRO2,HCRO2)
      IF(LELLB)RCRO2=RCRO2*HCRO2/SQRT(RCRO2**2+HCRO2**2)
C
      DO 1070 I=1,10
         IF(FDATA3(I+1) .NE. UNUSED)FDATA3(I+1)=FDATA3(I+1)+RCRO2
 1070 CONTINUE
C
 1080 CONTINUE
C
C  **  CALCULATION OF INLET GEOMETRY
C
      IF(LINLET) CALL GEOINL
C
      RETURN
      END
