      SUBROUTINE HYBRID(IPRINT,XX,RR,LNOS,VOVS,RN,AL,DIA,NBLUNT,
     1 BR,N,CAW,CNW,CMW,IERROR)
C
C***  MASTER ROUTINE FOR CONTROL OF VAN DYKE HYBRID THEORY
C
C  ROUTINE ADAPTED FROM NSWC AEROPREDICTION CODE
C  ORIGINAL ROUTINE WRITTEN BY F. MOORE, NSWC
C  MODIFIED BY J. JENKINS, WL/FIGC
C
      DIMENSION XX(50),RR(50),X(50),R(50)
C
      REAL LNOS
C
      CALL HYBINZ
C
      XO=0.
      IF(NBLUNT .EQ. 1)XO=XX(1)
C
      DO 1000 II=1,N
         X(II)=XX(II)-XO
         R(II)=RR(II)
 1000 CONTINUE
C
      NP1=N+1
C
      DO 1010 II=NP1,50
         X(II)=0.
         R(II)=0.
 1010 CONTINUE
C
      IERROR=0
C
      CALL HYBSET(X,R,XO,LNOS,BR,NSHAPE,N1,N2,N,N3,N4,DRB)
C
      IF(NBLUNT .EQ. 0)CALL HYBG1(N4,N3,IERROR,BETA,RP,X,R,N,
     1 NSHAPE,N1,N2,NN1,NN2,NN3,NN,VOVS,DRB)
      IF(NBLUNT .NE. 0)CALL HYBG2(N3,IERROR,BETA,RP,X,R,N,
     1 NSHAPE,N1,N2,NN1,NN2,NN3,NN,VOVS,BR,DRB)
C
      IF(IERROR .EQ. 1)GO TO 1020
C
      CALL VANDYK(IPRINT,BETA,RN,DIA,RP,R,N,NSHAPE,N2,NN1,NN2,
     1  NN3,NN4,NFL,NBLUNT,NN,NNI,VOVS,AL,XM,XINT,BR,IERROR,
     2  RREF,CAW,CNW,CMW)
C
 1020 CONTINUE
C
      CALL HYBINZ
C
      RETURN
      END
