      SUBROUTINE INZTRM
C
C***  INITIALIZE ALL TRIM ARRAYS
C
C***  INCIDENCE CONTROL DEVICES
C
      COMMON /INCID/ DELTA1(8),DELTA2(8),DELTA3(8),DELTA4(8),XHINGE(4),
     1               SKEW(4)
C
C***  TRIM INCIDENCE CONTROL
C
      COMMON /TRIMIN/ SET,PANL1,PANL2,PANL3,PANL4,PANL5,PANL6,PANL7,
     1                PANL8,DELMIN,DELMAX,ASYM(8)
      LOGICAL PANL1,PANL2,PANL3,PANL4,PANL5,PANL6,PANL7,PANL8,ASYM
C
      COMMON /UTRIMD/ DATAX(1200)
      COMMON /TRIMD/  TTRIM(120)
C
C***  TRIMMING DATA
C
C***  PROGRAM CONSTANTS
C
      COMMON /CONST/  PI,RAD,UNUSED,KAND
C
      SET=UNUSED
      PANL1=.FALSE.
      PANL2=.FALSE.
      PANL3=.FALSE.
      PANL4=.FALSE.
      PANL5=.FALSE.
      PANL6=.FALSE.
      PANL7=.FALSE.
      PANL8=.FALSE.
      DELMIN=UNUSED
      DELMAX=UNUSED
C
      XHINGE(1)=UNUSED
      XHINGE(2)=UNUSED
      XHINGE(3)=UNUSED
      XHINGE(4)=UNUSED
C
      SKEW(1)=UNUSED
      SKEW(2)=UNUSED
      SKEW(3)=UNUSED
      SKEW(4)=UNUSED
C
      DO 1000 I=1,8
         DELTA1(I)=UNUSED
         DELTA2(I)=UNUSED
         DELTA3(I)=UNUSED
         DELTA4(I)=UNUSED
         ASYM(I)=.FALSE.
 1000 CONTINUE
C
C     DO NOT INITIALIZE COMMON UTRIMD IF USING CONFIGURATION INCREMENTING
C
      DO 1010 I=1,1200
         DATAX(I)=UNUSED
 1010 CONTINUE
C
      DO 1020 I=1,120
         TTRIM(I)=UNUSED
 1020 CONTINUE
C
      RETURN
      END
