      SUBROUTINE LNTRP(ABSC,ORD,N,X,Y)
C
C***  SUBROUTINE TO LINEARILY INTERPOLATE A FUNCTION
C
C***  INPUTS
C
C   ABSC -- VALUES OF CURVE ABSCISSA (X-AXIS)
C    ORD -- VALUES OF CURVE ORDINATE (Y-AXIS)
C      N -- NUMBER OF POINTS IN CURVE
C      X -- ABSCISSA (X) VALUE TO BE INTERPOLATED
C
C***  OUTPUT
C
C      Y -- INTERPOLATED VALUE OF ORDINATE (Y)
C
      DIMENSION ABSC(N),ORD(N)
      LOGICAL ASCEND
C
      Y=ORD(1)
      IF(N .LE. 1)GO TO 1020
C
      IF(ABSC(1) .EQ. ABSC(2))GO TO 1020
C
      ASCEND=.TRUE.
C
C***  CHECK FOR DECENDING ABSC SEQUENCE
C
      IF(ABSC(2) .LT. ABSC(1))ASCEND=.FALSE.
C
C***  DETERMINE INTERVAL WHICH BRACKETS DESIRED X VALUE
C
      DO 1000 J=2,N
         I=J
         IF(.NOT. ASCEND)I=N-J+2
         IF(X .LT. ABSC(I))GO TO 1010
 1000 CONTINUE
C
 1010 CONTINUE
C
      IF(.NOT. ASCEND)I=I+1
      IF(I .LE. 1)I=2
      IF(I .GT. N)I=N
C
C***  LINEARILY INTERPOLATE/EXTRAPOLATE
C
      Y=ORD(I)
      IF((ABSC(I)-ABSC(I-1)) .EQ. 0.)GO TO 1020
C
      Y=ORD(I)-(ORD(I)-ORD(I-1))*(ABSC(I)-X)/(ABSC(I)-ABSC(I-1))
C
c     IF(X .LT. ABSC(1) .OR. X .GT. ABSC(N))CALL MESSG(X,Y,
c    1 ABSC(1),ABSC(N),ORD(1),ORD(N),1)
C
C
 1020 CONTINUE
C
      RETURN
      END
