      SUBROUTINE LVALUE(KOL,L,NDML,NF,BLANK,COMMA,NUMBER)
C
C***  SUBROUTINE TO TEST FOR LOGICAL VARIABLES AND SYNTAX
C
      COMMON /CONST/  PI,RAD,UNUSED,KAND
      DIMENSION KOL(80), NUMBER(15), TRUE(6), FALSE(7)
      LOGICAL STAR, NMTEST
C
      CHARACTER*4 TRUE,FALSE,KOL,BLANK,COMMA,NUMBER,KAND
C
      DATA TRUE  / '.   ','T   ','R   ','U   ','E   ','.   '/
      DATA FALSE / '.   ','F   ','A   ','L   ','S   ','E   ','.   '/
C
 1000 CONTINUE
      MULT = 0
      STAR = .FALSE.
      IF(L .GE. 81) GO TO 1080
      IF(KOL(L) .NE. BLANK) GO TO 1010
        L = L+1
        GO TO 1000
 1010 CONTINUE
C
C***  TEST FOR MULTIPLICATION FACTOR
C
      DO 1020 J=1,14
        IF(J .GE. 11 .AND. J .LE. 13) GO TO 1020
        IF(KOL(L) .EQ. NUMBER(J)) GO TO 1030
        IF(L .GE. 80) GO TO 1040
 1020 CONTINUE
      GO TO 1040
 1030 CONTINUE
      IF(STAR)      NF = NF+1
      IF(J .EQ. 14) STAR = .TRUE.
      IF(J .LE. 10) MULT = 10*MULT+J-1
      L = L+1
      GO TO 1010
 1040 CONTINUE
      IF(.NOT. STAR .AND. MULT .GT. 0) NF = NF+1
      IF(STAR .AND. MULT .EQ. 0)       NF = NF+1
      IF(MULT .EQ. 0) MULT = 1
C
C***  TEST FOR LOGICAL CONSTANTS
C
      NCHR = 6
      IF(NMTEST(KOL(L),TRUE,NCHR))  GO TO 1050
      NCHR = 7
      IF(NMTEST(KOL(L),FALSE,NCHR)) GO TO 1050
      GO TO 1080
 1050 CONTINUE
      L = L+NCHR
 1060 CONTINUE
      IF(L .GE. 80) GO TO 1070
      IF(KOL(L) .NE. BLANK) GO TO 1070
        NF = NF+1
        L = L+1
        GO TO 1060
 1070 CONTINUE
      IF(KOL(L) .NE. COMMA .AND. KOL(L) .NE. KAND) NF = NF+1
      IF(KOL(L) .EQ. COMMA) L = L+1
      NDML = NDML+MULT
      GO TO 1000
C
C***  END OF CARD OR NON-LOGICAL VARIABLE FOUND
C
 1080 CONTINUE
      IF(NDML .EQ. 0) NF = NF+1
      RETURN
      END
