      SUBROUTINE MVLOOK(KGRAPH,KCURVE,KPOINT,NPTS,FGRAPH,FCURVE,
     1 XCURVE,YCURVE,ARGX,ARGCUR,ARGGPH,ANS)
C
C***  SUBROUTINE TO PERFORM A MULTI-VARIABLE TABLE LOOKUP
C
C***  INPUTS
C
C KGRAPH -- NUMBER OF GRAPHS IN SET
C KCURVE -- NUMBER OF CURVES ON EACH GRAPH
C KPOINT -- NUMBER OF POINTS ON EACH CURVE
C   NPTS -- TOTAL NUMBER OF POINTS, KGRAPH*KCURVE*KPOINT
C FGRAPH -- TABLE GIVING VALUES FOR EACH GRAPH
C FCURVE -- TABLE GIVING VALUES FOR EACH CURVE
C XCURVE -- TABLE OF X VALUES (COMMON FOR EACH CURVE)
C YCURVE -- TABLE OF Y VALUES FOR EACH CURVE
C   ARGX -- VALUE OF X FOR INTERPOLATION
C ARGCUR -- VALUE OF CURVE FOR INTERPOLATION
C ARGGPH -- VALUE OF GRAPH FOR INTERPOLATION
C
C***  OUTPUT
C
C    ANS -- INTERPOLATED VALUE
C
      DIMENSION FGRAPH(KGRAPH),FCURVE(KCURVE),XCURVE(KPOINT),
     1 YCURVE(NPTS),X(50),Y1(50),Y2(50),Y3(50)
C
      L=0
C
      DO 1020 I=1,KGRAPH
         DO 1010 J=1,KCURVE
            DO 1000 K=1,KPOINT
               L=L+1
               X(K)=XCURVE(K)
               Y1(K)=YCURVE(L)
 1000       CONTINUE
            CALL LNTRP(X,Y1,KPOINT,ARGX,ANS)
            Y2(J)=ANS
 1010    CONTINUE
         CALL LNTRP(FCURVE,Y2,KCURVE,ARGCUR,ANS)
         Y3(I)=ANS
 1020 CONTINUE
C
      CALL LNTRP(FGRAPH,Y3,KGRAPH,ARGGPH,ANS)
C
      RETURN
      END
