      SUBROUTINE NDIV(XL, DX, NP)
C
C     CALCULATE THE NUMBER OF DIVISIONS IN XL AND INCREASE
C     TO AN EVEN NUMBER
C
C     INPUT VARIABLES
C         XL - SEGMENT LENGTH
C         DX - NOMINAL INCREMENT SIZE
C
C     OUTPUT VARIABLE
C         NP - NUMBER OF DIVISIONS
C
      NP = 0.5+XL/DX
      IF(NP .LT. 2)NP=2
      NN = NP/2
      NN = 2*NN
      IF(NN .LT. NP) NP = NP+1
C
      RETURN
      END
