      SUBROUTINE PACK(KOL,END)
C
C***  SUBROUTINE TO PACK THE NAMELIST INPUT CARD STARTING IN COLUMN 2
C***  OR CONTROL CARDS IN COLUMN 1
C
      COMMON /CONST/  PI,RAD,UNUSED,KAND
C
      CHARACTER*4 KAND,IBLANK,ICOMMA,IEQUAL,IPOINT,IEND,KOL,ICARD
C
      DIMENSION KOL(80),ICARD(80),IEND(3)
      LOGICAL END
      DATA IBLANK / '    ' /
      DATA ICOMMA / ',   ' /
      DATA IEQUAL / '=   ' /
      DATA IPOINT / '.   ' /
      DATA IEND / 'E   ','N   ','D   '/
C
C***  EXIT IF COLUMN 1 IS NOT BLANK
C
      IF(KOL(1).NE.IBLANK)GO TO 1080
C
C***  PACK NEW CARD IMAGE WITH BLANKS
C
      DO 1000 I=1,80
         ICARD(I)=IBLANK
 1000 CONTINUE
C
C***  FIND FIRST NON-BLANK CARD COLUMN
C
      DO 1010 I=1,80
         II=I
         IF(KOL(I).NE.IBLANK)GO TO 1020
 1010 CONTINUE
      GO TO 1080
 1020 CONTINUE
C
C***  CHECK IF CONTROL CARD
C
      IF(END .AND. KOL(II).NE.KAND)GO TO 1090
C
      IF(KOL(II).NE.KAND)GO TO 1050
C
C***  SHIFT TO CARD COLUMN 2
C
      IIM2=II-2
      DO 1030 I=II,80
         IJ=I-IIM2
         ICARD(IJ)=KOL(I)
 1030 CONTINUE
C
C***  PUT NEW CARD INTO OLD CARD IMAGE
C
      DO 1040 I=1,80
         KOL(I)=ICARD(I)
 1040 CONTINUE
C
C***  VERIFY LAST NON-BLANK CHARACTER IS A COMMA, $ OR $END
C
 1050 DO 1060 I=1,80
         II=80-I+1
         IF(KOL(II).EQ.IBLANK)GO TO 1060
         IF(KOL(II).NE.ICOMMA)GO TO 1070
         GO TO 1080
 1060 CONTINUE
      GO TO 1080
 1070 IF(KOL(II).EQ.KAND .OR. (KOL(II-3).EQ.KAND .AND. KOL(II-2).EQ.
     1  IEND(1) .AND. KOL(II-1).EQ.IEND(2) .AND. KOL(II).EQ.IEND(3)))
     2  GO TO 1080
C
C***  CHECK FOR NO BLANKS TO $
C
      DO 1072 I=2,II
         ICC=II+2-I
         IF(KOL(ICC) .EQ. IBLANK)GO TO 1074
         IF(KOL(ICC) .EQ. IPOINT)GO TO 1074
         IF(KOL(ICC) .EQ. IEQUAL)GO TO 1074
         IF(KOL(ICC) .EQ. ICOMMA)GO TO 1074
         IF(KOL(ICC) .EQ. KAND)GO TO 1080
 1072 CONTINUE
      GO TO 1080
 1074 IF(II.LT.80)KOL(II+1)=ICOMMA
 1080 CONTINUE
      GO TO 1120
 1090 CONTINUE
C
C***  HERE FOR CONTROL CARD
C
      IL=0
      DO 1100 I=II,80
         IL=IL+1
         ICARD(IL)=KOL(I)
 1100 CONTINUE
      DO 1110 I=1,80
         KOL(I)=ICARD(I)
 1110 CONTINUE
C
 1120 CONTINUE
      RETURN
      END
