      SUBROUTINE PLTTRM(IM)
C
C***  SUBROUTINE TO GENERATE A PLOT FILE ON TAPE UNIT 3
C***  OF TRIMMING RESULTS FOR POST PROCESSING BY A PLOTTING PROGRAM
C
      COMMON /CASEID/ IDCASE(74),KOUNT,NAMSV(100),CASE,NOEXTR,NOLAT,
     1                IR,IPAGE
      COMMON /REFQN/  SREF,LREF,LATREF,ROUGH,XCG,ZCG,SCALE,BLAYER,RHR
      COMMON /FLC/    NALPHA,ALPHA(20),BETA,PHI,NMACH,MACH(20),
     1                ALT(20),REN(20),VINF(20),TINF(20),PINF(20)
      COMMON /CONST/  PI,RAD,UNUSED,KAND
      COMMON /LOGIC/ LDMPCS,LDAMP,LBUILD,LNACA,LDERDG,
     1               LDERRD,LPART,LNAME,LPLOT,
     2               LFLT,LREFQ,LAXIS,LFIN1,LFIN2,LFIN3,LFIN4,
     3               LDEFL,LTRIM,LDIMIN,LDIMFT,LDIMCM,LDIMM,LELLB,
     4               LINLET,LEXPR,LICRMT,LSPIN,LARBOD
      LOGICAL        LDMPCS,LDAMP,LBUILD,LNACA,LDERDG,
     1               LDERRD,LPART,LNAME,LPLOT,
     2               LFLT,LREFQ,LAXIS,LFIN1,LFIN2,LFIN3,LFIN4,
     3               LDEFL,LTRIM,LDIMIN,LDIMFT,LDIMCM,LDIMM,LELLB,
     4               LINLET,LEXPR,LICRMT,LSPIN,LARBOD
      COMMON /UTRIMD/CN(200),CM(200),CA(200),CY(200),
     1               CLN(200),CLL(200)
      COMMON /TRIMD/ DELTRM(20),CNTRM(20),CATRM(20),
     1               CYTRM(20),CLNTRM(20),CLLTRM(20)
      DIMENSION IC(10)
C
      REAL NALPHA,NMACH,MACH,LREF,LATREF
      INTEGER CASE
      CHARACTER*4 PIN,PFT,PCM,PM,IC,IPTYP
C
      DATA PIN / 'I   '/
      DATA PFT / 'F   '/
      DATA PCM / 'C   '/
      DATA PM  / 'M   '/
      DATA IC /'D1  ','D2  ','D3  ','D4  ','D5  ','D6  ','D7  ',
     1         'D8  ','D9  ','D10 '/
C
      NALP=NALPHA+0.5
C
      IPTYP=PFT
      IF(LDIMIN)IPTYP=PIN
      IF(LDIMCM)IPTYP=PCM
      IF(LDIMM )IPTYP=PM
C
      CALL CVRTFT
C
      IR=IR+1
C
C  REV 6/93 AND PRIOR VERSION CODE COMMENTED OUT
C  TECPLOT FORMAT USED FOR REV 5/97
C
C     WRITE(3,1030)IR,NALP,IPTYP,CASE
C     WRITE(3,1050)MACH(IM),REN(IM),PHI
C     WRITE(3,1060)SREF,LREF,XCG,LATREF,ZCG
      WRITE(3,1100) MACH(IM)
      DO 1000 I=1,NALP
      TCL=CNTRM(I)*COS(ALPHA(I)*PI/180.)-CATRM(I)*SIN(ALPHA(I)*PI/180.)
      TCD=CATRM(I)*COS(ALPHA(I)*PI/180.)+CNTRM(I)*SIN(ALPHA(I)*PI/180.)
         WRITE(3,1070)ALPHA(I),CNTRM(I),0.,CATRM(I),
     1                CYTRM(I),CLNTRM(I),CLLTRM(I),DELTRM(I),TCL,TCD
 1000 CONTINUE
C
C     WRITE(3,1080)
C
      DO 1020 IDELT=1,10
C
      IR=IR+1
C
C  REV 6/93 AND PRIOR VERSION CODE COMMENTED OUT
C
C     WRITE(3,1040)IR,NALP,IPTYP,IC(IDELT),CASE
C     WRITE(3,1050)MACH(IM),REN(IM),PHI
C     WRITE(3,1060)SREF,LREF,XCG,LATREF,ZCG
C
C     DO 1010 I=1,NALP
C        J=(IDELT-1)*20+I
C        WRITE(3,1070)ALPHA(I),CN(J),CM(J),CA(J),CY(J),CLN(J),CLL(J)
C1010 CONTINUE
C
C     WRITE(3,1080)
C
 1020 CONTINUE
C
      CALL CVRTUS
C
C1030 FORMAT('RUN',I4,I3,2X,A1,' TRIMMED',3X,'CASE ',I3)
C1040 FORMAT('RUN',I4,I3,2X,A1,A4,6X,'CASE ',I3)
C1050 FORMAT(F10.4,F10.0,F10.4)
C1060 FORMAT(5F10.4)
 1070 FORMAT(F7.2,9F10.4)
C1080 FORMAT('R')
 1100 FORMAT('ZONE T="TRIMMED MACH=',F6.2,'"')
C
      RETURN
      END
