      SUBROUTINE PRIFIN
C
C***  SUBROUTINE TO CONTROL THE PRINTING OF FIN RESULTS FROM THE
C***  GEOMETRIC CALCULATIONS
C
      COMMON /PARTF/ PARTS(19)
      LOGICAL PARTS
      COMMON /LOGIC/ LDMPCS,LDAMP,LBUILD,LNACA,LDERDG,
     1               LDERRD,LPART,LNAME,LPLOT,
     2               LFLT,LREFQ,LAXIS,LFIN1,LFIN2,LFIN3,LFIN4,
     3               LDEFL,LTRIM,LDIMIN,LDIMFT,LDIMCM,LDIMM,LELLB,
     4               LINLET,LEXPR,LICRMT,LSPIN,LARBOD
      LOGICAL        LDMPCS,LDAMP,LBUILD,LNACA,LDERDG,
     1               LDERRD,LPART,LNAME,LPLOT,
     2               LFLT,LREFQ,LAXIS,LFIN1,LFIN2,LFIN3,LFIN4,
     3               LDEFL,LTRIM,LDIMIN,LDIMFT,LDIMCM,LDIMM,LELLB,
     4               LINLET,LEXPR,LICRMT,LSPIN,LARBOD
C
      IF(.NOT.(PARTS(2).OR.PARTS(3).OR.PARTS(4).OR.PARTS(5)))GO TO 1020
C
      CALL HEADR9
C
      WRITE(6,1000)
C
C***  CONVERT DATA TO USER UNITS IF NEEDED
C
      IF(LDIMIN .OR. LDIMCM .OR. LDIMM)CALL CVRTFT
C
      IF(LFIN1.AND.PARTS(2))CALL PRIF1
C
      WRITE(6,1010)
      IF(LFIN2.AND.PARTS(3))CALL PRIF2
C
      WRITE(6,1010)
      IF(LFIN3.AND.PARTS(4))CALL PRIF3
C
      WRITE(6,1010)
      IF(LFIN4.AND.PARTS(5))CALL PRIF4
C
C***  CONVERT DATA TO INTERNAL UNITS IF NEEDED
C
      IF(LDIMIN .OR. LDIMCM .OR. LDIMM)CALL CVRTUS
C
 1000 FORMAT(22X,'GEOMETRIC RESULTS FOR FIN SETS',/)
 1010 FORMAT(' ')
C
 1020 CONTINUE
C
      RETURN
      END
