      SUBROUTINE PRINT(IM)
C
C***  PRINT THE RESULTS COMPUTED
C
      COMMON /LOGIC/ LDMPCS,LDAMP,LDUM2(26)
      COMMON /PARTF/ PARTS(19)
      LOGICAL PARTS,LDMPCS,LDAMP
C
C ** PRINT AUXILIARY DATA IF REQUIRED
C
      CALL SAVEF
C
C ** PRINT/PLOT AERODYNAMIC OUTPUT (STATICS)
C
      IF(PARTS(19))CALL PRINTS(IM)
C
C ** PRINT DYNAMIC DERIVATIVES IF CALCULATED
C
      IF(LDAMP)CALL DWRIT2(IM)
      RETURN
      END
