      SUBROUTINE SRATIO(MACH,LMACH,DELTA,RATIO,A2)
C
C *** CALCULATES THE COEFFICIENTS USED TO COMPUTE
C *** THE MODIFIED DAHLEM-BUCK PRESSURE COEFFICIENT
C
C ***   A1 = A
C ***   A2 = -N
C ***   LMACH = NATURAL LOG OF FREE STREAM MACH NUMBER
C
      REAL MACH,LMACH
      COMMON /CONST/PI,RAD,UNUSED,KAND
C
      A1=(6.-.3*MACH)+SIN((LMACH-.588)/1.20*PI)
      A2=1.15+0.5*SIN((LMACH-0.916)/3.29*PI)
      RATIO=A1*(DELTA*RAD)**(-A2)+1.0
      RETURN
      END
