      SUBROUTINE WRITNL
C
C***  WRITE OUT NAMELISTS
C
      COMMON /LOGIC/ LDMPCS,LDAMP,LBUILD,LNACA,LDERDG,
     1               LDERRD,LPART,LNAME,LPLOT,
     2               LFLT,LREFQ,LAXIS,LFIN1,LFIN2,LFIN3,LFIN4,
     3               LDEFL,LTRIM,LDIMIN,LDIMFT,LDIMCM,LDIMM,LELLB,
     4               LINLET,LEXPR,LICRMT,LSPIN,LARBOD
      LOGICAL        LDMPCS,LDAMP,LBUILD,LNACA,LDERDG,
     1               LDERRD,LPART,LNAME,LPLOT,
     2               LFLT,LREFQ,LAXIS,LFIN1,LFIN2,LFIN3,LFIN4,
     3               LDEFL,LTRIM,LDIMIN,LDIMFT,LDIMCM,LDIMM,LELLB,
     4               LINLET,LEXPR,LICRMT,LSPIN,LARBOD
      IF(LFLT)CALL WRFLT
      IF(LREFQ)CALL WRREFQ
      IF(LAXIS)CALL WRAXIS
      IF(LFIN1)CALL WRFIN1
      IF(LFIN2)CALL WRFIN2
      IF(LFIN3)CALL WRFIN3
      IF(LFIN4)CALL WRFIN4
      IF(LDEFL)CALL WRDEFL
      IF(LTRIM)CALL WRTRIM
      IF(LELLB)CALL WELLB
      IF(LINLET)CALL WINLET
      IF(LARBOD)CALL WARBOD
      RETURN
      END
