      SUBROUTINE ALPBET(ALPHA,ALPTOT,BETA,PHI)
C
C***  COMPUTE TOTAL ANGLE OF ATTACK AND AERODYNAMIC ROLL IF
C***  ANGLE OF ATTACK AND SIDESLIP ANGLE DEFINED
C
C***  COMPUTE ANGLE OF ATTACK AND SIDESLIP ANGLE IF TOTAL ANGLE
C***  OF ATTACK AND AERODYNAMIC ROLL DEFINED
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      IF(ABS(PHI) .GT. UNUSED)GO TO 1000
C
C***  PHI NOT DEFINED OR ZERO, ASSUME ALPHA/BETA INPUT
C
      ALPTOT=ATAN(SQRT((TAN(ALPHA/RAD))**2+(TAN(BETA/RAD))**2))*RAD
C
C***  EVALUATION OF AERODYNAMIC ROLL DEPENDENT UPON ALPHA AND BETA
C
      IF(ALPHA.EQ.0. .AND. BETA.EQ.0.) PHI=0.
      IF(ALPHA.NE.0. .AND. BETA.NE.0.) PHI=ATAN(TAN(BETA/RAD)/
     1                                     TAN(ALPHA/RAD))*RAD
      IF(ALPHA.EQ.0. .AND. BETA.NE.0.) PHI=90.*BETA/ABS(BETA)
C
      IF(ALPHA .GE. 0.)GO TO 1010
C
      IF(BETA.GE.0.) PHI=PHI+180
      IF(BETA .LT. 0.) PHI=PHI-180.
C
      GO TO 1010
C
 1000 CONTINUE
C
C***  PHI DEFINED, ASSUME TOTAL ANGLE OF ATTACK INPUT
C
      ALPHA = ATAN(TAN(ALPTOT/RAD)*COS(PHI/RAD))*RAD
      BETA  = -ATAN(TAN(ALPTOT/RAD)*SIN(PHI/RAD))*RAD
C
 1010 CONTINUE
C
      RETURN
      END
