      SUBROUTINE BDCAPR(FR,CAF,CAPR)
C
C***  SUBROUTINE TO COMPUTE THE SUBSONIC PRESSURE DRAG FOR A BODY
C***  METHOD FROM DATCOM SECTION 4.2.3.1
C
C***  INPUTS
C
C     FR -- BODY FINENESS RATIO (LENGTH/MAX. DIAMETER)
C    CAF -- AXIAL FORCE DUE TO SKIN FRICTION
C
C***  OUTPUT
C
C   CAPR -- INCREMENT IN AXIAL FORCE DUE TO PRESSURE DRAG
C
C***  FORM FACTOR MULTIPLIER TO FRICTION DRAG METHOD USED
C
      FORM=1.+60./FR**3+0.0025*FR
C
      CAPR=(FORM-1.)*CAF
C
      RETURN
      END
