      SUBROUTINE BDCALP(ALPHA,CN,CAO,CADB)
C
C***  SUBROUTINE TO COMPUTE THE DRAG DUE TO LIFT FOR AXISYMMETRIC
C***  BODIES USING THE METHOD OF ALLEN AND PERKINS
C
C***  INPUTS
C
C  ALPHA -- ANGLE OF ATTACK, DEGREES
C     CN -- NORMAL FORCE COEFFICIENT AT ALPHA
C    CAO -- AXIAL FORCE COEFFICIENT AT ZERO NORMAL FORCE
C
C***  OUTPUT
C
C   CADB -- AXIAL FORCE AT ANGLE OF ATTACK (EXCLUDING CAO)
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
C***  COMPUTE THE LIFT COEFFICIENT
C
      CL=(CN-CAO*SIN(ALPHA/RAD))/(COS(ALPHA/RAD)+SIN(ALPHA/RAD)**2)
C
C***  THE DRAG COEFFICIENT
C
      CD=CAO+CL*SIN(ALPHA/RAD)
C
C***  TOTAL AXIAL FORCE COEFFICIENT
C
      CA=CD*COS(ALPHA/RAD)-CL*SIN(ALPHA/RAD)
C
C***  AXIAL FORCE AT ANGLE OF ATTACK
C
      CADB=CA-CAO
C
      RETURN
      END
