      SUBROUTINE BDCDRV(TAFT,DCENTR,DAFT,LAFT,MACH,LTHEO,CAPBT)
C
C***   THIS ROUTINE CONTROLS CALCULATION OF SUBSONIC/TRANSONIC
C***   BOATTAIL PRESSURE DRAG.
C
C***   INPUTS
C
C***       TAFT -- SHAPE PARAMETER.
C***               .EQ. 0.    USE CONICAL METHOD
C***               .NE. 0.    USE OGIVAL METHOD
C***     DCENTR -- FORWARD BOATTAIL DIAMETER
C***       DAFT -- AFT BOATTAIL DIAMETER
C***       LAFT -- LENGTH OF AFTERBODY
C***       MACH -- FREESTREAM MACH NUMBER
C***      LTHEO -- THEORETICAL LENGTH OF BOATTAIL
C
C***   OUTPUT
C
C***      CAPBT -- PRESSURE DRAG INCREMENT TO AXIAL FORCE BASED ON
C***               MAXIMUM CROSS-SECTIONAL AREA
C
      REAL MACH,LAFT,LTHEO
C
C***  SELECT CONICAL METHOD
C
      IF(TAFT.EQ.0.) CALL BDCAP1(DCENTR,DAFT,LAFT,MACH,LTHEO,CAPBT)
C
C***  SELECT OGIVAL METHOD
C
      IF(TAFT.NE.0.) CALL BDCAP2(DCENTR,DAFT,LAFT,MACH,LTHEO,CAPBT)
C
      RETURN
      END
