      SUBROUTINE BDCMP(CMALP,ALPHA,CMP)
C
C***  SUBROUTINE TO COMPUTE THE POTENTIAL PITCHING MOMENT FOR BODIES
C***  METHOD OF ALLEN AND PERKINS
C
C  MODIFIED BY W. BLAKE, WL/FIGC
C
C***  INPUTS
C
C  CMALP -- PITCHING MOMENT SLOPE, PER RADIAN
C  ALPHA -- ANGLE OF ATTACK, DEGREES
C
C***  OUTPUT
C
C    CMP -- POTENTIAL PITCHING MOMENT COEFFICIENT AT ANGLE OF ATTACK
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
C  REV 3/99 CORRECT CALCULATION FOR ALPHA > 90 OR < -90
C
      ALP=ALPHA
      IF(ALPHA.GT.90.)  ALP=ALPHA-180.
      IF(ALPHA.LT.-90.) ALP=180.-ALPHA
      CMP=CMALP/2.*SIN(2.*ALP/RAD)*COS(ALP/RAD/2.)
C
      RETURN
      END
