      SUBROUTINE BDXCPF(DFWD,DAFT,FOREL,FLAREL,XCPFLR)
C
C  COMPUTE THE SUBSONIC/TRANSONIC FLARE CENTER OF PRESSURE
C
C  METHOD FROM AMC PAMPHLET AMCP 706-280, JULY 1968
C
C***  INPUTS
C
C   DFWD - DIAMETER OF FORWARD END OF THE FLARE
C   DAFT - DIAMETER OF THE AFT END OF THE FLARE
C  FOREL - LENGTH OF BODY FORWARD OF FLARE
C FLAREL - LENGTH OF THE FLARE
C
C***  OUTPUT
C
C XCPFLR - FLARE CENTER OF PREESURE AFT OF FORWARD DIAMETER,
C            BASED ON DFWD (POSITIVE AFT OF FORWARD DIAMETER LOC.)
C
      XCPFLR=0.
C
      IF(DFWD .EQ. DAFT .OR. DAFT .EQ. 0.)GO TO 1000
C
      XCPFLR=-(DFWD/DAFT*(DFWD/DAFT+1.)-2.)/3./(1.-(DFWD/DAFT)**2)
     1       *FLAREL/DFWD+FOREL/DFWD
C
 1000 CONTINUE
C
      RETURN
      END
