      SUBROUTINE BODYA(IM)
C
C***  EXECUTIVE FOR AXISYMMETRIC BODY ALONE AERODYNAMICS
C
C***  IM IS THE CURRENT MACH NUMBER INDEX
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
      COMMON /ABODIN/ NX,X0,X(50),R(50),TNOSE,LNOSE,DNOSE,BNOSE,
     1                TRUNC,LCENTR,DCENTR,TAFT,LAFT,DAFT,POWER,
     2                DISCON(20),ELLIP(50),H(50),ADUM(648)
      REAL NX,LNOSE,LCENTR,LAFT
      COMMON /REFQN/  SREF,LREF,LATREF,ROUGH,XCG,ZCG,SCALE,BLAYER,RHR
      REAL LREF,LATREF
      COMMON /FLC/    NALPHA,ALPHA(20),BETA,PHI,NMACH,MACH(20),
     1                ALT(20),REN(20),VINF(20),TINF(20),PINF(20)
      REAL NALPHA,NMACH,MACH
      COMMON /TOTALC/ BALPHA(20),BBETA(20),BPHI(20),ALPTOT(20)
C
      COMMON /SBODY/ CNB(20),CMB(20),CAB(20),CYB(20),CLNB(20),CLLB(20),
     1               CNAB(20),CMAB(20),CYBB(20),CNBB(20),CLBB(20)
      COMMON /BDWORK/ CNP(20),CMP(20),CNV(20),CMV(20),DUM(161)
C
      COMMON /PARTF/ PARTS(19)
      LOGICAL PARTS
      COMMON /LOGIC/ LDMPCS,LDAMP,LBUILD,LNACA,LDERDG,
     1               LDERRD,LPART,LNAME,LPLOT,
     2               LFLT,LREFQ,LAXIS,LFIN1,LFIN2,LFIN3,LFIN4,
     3               LDEFL,LTRIM,LDIMIN,LDIMFT,LDIMCM,LDIMM,LELLB,
     4               LINLET,LEXPR,LICRMT,LSPIN,LARBOD
      LOGICAL        LDMPCS,LDAMP,LBUILD,LNACA,LDERDG,
     1               LDERRD,LPART,LNAME,LPLOT,
     2               LFLT,LREFQ,LAXIS,LFIN1,LFIN2,LFIN3,LFIN4,
     3               LDEFL,LTRIM,LDIMIN,LDIMFT,LDIMCM,LDIMM,LELLB,
     4               LINLET,LEXPR,LICRMT,LSPIN,LARBOD
C
C***  CALL SUBSONIC/TRANSONIC OR SUPERSONIC METHOD SUBROUTINES
C
C     * IF THE CURRENT MACH NUMBER IS LESS THAN 1.2
           IF(MACH(IM) .LE. 1.2)GO TO 1000
           GO TO 1010
C       THEN USE SUBSONIC OR TRANSONIC METHODS
 1000      CALL STBODY(IM)
           GO TO 1020
C       ELSE USE SUPERSONIC METHODS
 1010      CONTINUE
           CALL SUPBOD(IM)
 1020      CONTINUE
C     * ENDIF
C
C***  DIFFERENTIATE CN AND CM CURVES, SET ROLL MOMENT EQUAL TO ZERO
C
      NALP=NALPHA+0.5
      DO 1030 I=1,NALP
         CALL POLINT(ALPHA,CNB,NALP,ALPHA(I),CNBINT,CNAB(I))
         CALL POLINT(ALPHA,CMB,NALP,ALPHA(I),CMBINT,CMAB(I))
         CLLB(I)=0.
         CLBB(I)=0.
 1030 CONTINUE
C
C***  DIRECTIONAL DERIVATIVES (PERTURBATING BETA BY ONE DEGREE)
C
      DO 1040 I=1,NALP
         BETNEW=BBETA(I)+1.
         PHINEW=UNUSED
         CALL ALPBET(BALPHA(I),ALTNEW,BETNEW,PHINEW)
         CALL POLINT(BALPHA,CNB,NALP,ALTNEW,CNNPHI,DYDX)
         CYBB(I)=-CYB(I)-SIN(PHINEW/RAD)*CNNPHI
 1040 CONTINUE
C
      DO 1050 I=1,NALP
         BETNEW=BBETA(I)+1.
         PHINEW=UNUSED
         CALL ALPBET(BALPHA(I),ALTNEW,BETNEW,PHINEW)
         CALL POLINT(BALPHA,CMB,NALP,ALTNEW,CMNPHI,DYDX)
         CNBB(I)=-CLNB(I)-SIN(PHINEW/RAD)*CMNPHI*LREF/LATREF
 1050 CONTINUE
C
      IF(PARTS(6))CALL BDPART(IM,1.,1.,1.,1.,1.,1.,1.,1.)
C
      RETURN
      END
