      SUBROUTINE BUILD(MACH,RPUL,DEL,K,KK,NM,BDTYPE,HPROT,
     * WPROT,LPROT,OPROT,CDBILD)
C
C  WRITTEN BY K. DETERS, MCDONNELL DOUGLAS
C
      REAL MACH,BDTYPE(100),HPROT(100),WPROT(100),LPROT(100),
     * OPROT(100)
      CDTOT=0.0
      DO 10 I=1,NM
      K=K+1
      KK=KK+1
      ITYPE=BDTYPE(KK)
      IF (ITYPE .EQ. 1)
     * CALL CYL(MACH,RPUL,DEL,HPROT(K),WPROT(K),LPROT(K),OPROT(K),CDSUM)
      IF (ITYPE .EQ. 2)
     * CALL CIRC(MACH,DEL,HPROT(K),LPROT(K),OPROT(K),CDSUM)
      IF (ITYPE .EQ. 5)
     * CALL FLAT(MACH,DEL,HPROT(K),WPROT(K),LPROT(K),OPROT(K),CDSUM)
      CDTOT=CDTOT+CDSUM
 10   CONTINUE
      CDBILD=CDTOT
      RETURN
      END
