      SUBROUTINE CLOCD(ALPHA,CN,CA,CL,CD,CLCD)
C
C***  SUBROUTINE TO COMPUTE THE LIFT, DRAG AND LIFT/DRAG
C***  COEFFICIENTS FROM THE NORMAL FORCE AND AXIAL FORCE
C***  COEFFICIENTS
C
C***  INPUTS
C
C  ALPHA -- ANGLE OF ATTACK, DEGREES
C     CN -- NORMAL FORCE COEFFICIENT
C     CA -- AXIAL FORCE COEFFICIENT
C
C***  OUTPUTS
C
C     CL -- LIFT COEFFICIENT
C     CD -- DRAG COEFFICIENT
C   CLCD -- LIFT DIVIDED BY DRAG COEFFICIENT
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      CL=UNUSED
      CD=UNUSED
      CLCD=1./UNUSED
C
      IF(ALPHA .EQ. UNUSED)GO TO 1000
      IF(CN .EQ. UNUSED .OR. CA .EQ. UNUSED)GO TO 1000
C
      CL=CN*COS(ALPHA/RAD)-CA*SIN(ALPHA/RAD)
      CD=CA*COS(ALPHA/RAD)+CN*SIN(ALPHA/RAD)
C
      IF(CD .NE. 0.)CLCD=CL/CD
      IF(CD .EQ. 0.)CLCD=1./UNUSED
C
 1000 CONTINUE
C
      RETURN
      END
