      SUBROUTINE CUBIC(X,X1,X2,Y1,Y2,DY1,DY2,Y)
C***  THIS PROGRAM FAIRS BETWEEN TWO POINTS USING A
C***  CUBIC SPLINE
C
C***  CALCULATE COEFFICIENTS
      A=(DY1+DY2)/(X1-X2)**2-2.*(Y1-Y2)/(X1-X2)**3
      B=(DY1-DY2)/(2.*(X1-X2))-1.5*(X1+X2)*A
      C=DY1-2.*B*X1-3.*A*X1**2
      D=Y1-C*X1-B*X1**2-A*X1**3
C
C***  CALCULATE Y AS A FUNCTION OF X
      Y=A*X**3+B*X**2+C*X+D
      RETURN
      END

