      SUBROUTINE CVRFLT(ISIGN)
C
C***  ROUTINE TO CONVERT THE DATA IN THE FLIGHT CONDITIONS
C***  DATA BLOCKS BETWEEN THE USER AND FOOT SYSTEM OF UNITS
C
C ISIGN=+1 CONVERTS FROM FT-LB SYSTEM TO USER SYSTEM
C ISIGN=-1 CONVERTS FROM USER SYSTEM TO FT-LB SYSTEM
C
      COMMON /FLC/    NALPHA,ALPHA(20),BETA,PHI,NMACH,MACH(20),
     1                ALT(20),REN(20),VINF(20),TINF(20),PINF(20)
      COMMON /CONST/  PI,RAD,UNUSED,KAND
C
      REAL NALPHA,NMACH,MACH
      COMMON /LOGIC/  LFLAGS(18),LDIMIN,LDIMFT,LDIMCM,LDIMM,LDUM2(6)
C
      LOGICAL         LFLAGS    ,LDIMIN,LDIMFT,LDIMCM,LDIMM
C
      IF(LDIMIN .OR. LDIMFT)GO TO 1020
      IF(.NOT. (LDIMCM .OR. LDIMM))GO TO 1020
C
C***  CONVERT ALTITUDE,
C             VELOCITY, TEMPERATURE, REYNOLDS NUMBER AND PRESSURE
C
         DO 1010 I=1,20
         IF(ISIGN .LT. 0 .AND. ALT(I) .NE. UNUSED) ALT(I)=ALT(I)*3.28
         IF(ISIGN .GT. 0 .AND. ALT(I) .NE. UNUSED) ALT(I)=ALT(I)/3.28
            IF(ISIGN.LT.0 .AND. VINF(I).NE.UNUSED) VINF(I)=VINF(I)*3.28
            IF(ISIGN.GT.0 .AND. VINF(I).NE.UNUSED) VINF(I)=VINF(I)/3.28
            IF(ISIGN.LT.0 .AND. REN(I).NE.UNUSED) REN(I)=REN(I)/3.28
            IF(ISIGN.GT.0 .AND. REN(I).NE.UNUSED) REN(I)=REN(I)*3.28
            IF(ISIGN .LT. 0 .AND. PINF(I) .NE. UNUSED)
     1         PINF(I)=PINF(I)/47.88
            IF(ISIGN .LT. 0 .AND. TINF(I) .NE. UNUSED)
     1         TINF(I)=TINF(I)*9./5.
            IF(ISIGN .GT. 0 .AND. PINF(I) .NE. UNUSED)
     1         PINF(I)=PINF(I)*47.88
            IF(ISIGN .GT. 0 .AND. TINF(I) .NE. UNUSED)
     1         TINF(I)=TINF(I)*5./9.
 1010    CONTINUE
 1020 CONTINUE
C
      RETURN
      END
