      SUBROUTINE CVRTUS
C
C***  ROUTINE TO CONVERT ALL INPUT AND DATA ARRAYS FROM
C***  UNITS THAT ARE USER DEFINED TO UNITS OF FEET
C
C ... FLIGHT CONDITIONS
C
      CALL CVRFLT(-1)
C
C ... REFERENCE QUANTITIES
C
      CALL CVRREF(-1)
C
C ... BODY DATA
C
      CALL CVRBOD(-1)
C
C ... FIN DATA
C
      CALL CVRFIN(-1)
C
      RETURN
      END
