      SUBROUTINE DIHED(PHI,GAMMA)
C
C  THIS SUBROUTINE CALCULATES THE FIN DIHEDRAL ANGLE
C
C *** INPUTS ***
C
C    PHI - FIN ROLL ORIENTATION
C
C *** OUTPUT ***
C
C  GAMMA - DIHEDRAL ANGLE, DEG.
C
      PHIA = ABS(PHI)
      IF(PHIA .GT. 180.0) PHIA = 360.0-PHIA
      GAMMA = 90.0-PHIA
      RETURN
      END
