      FUNCTION DSWETE(NPTS,X,A,B)
C
C** FUNCTION TO COMPUTE THE WETTED AREA OF AN ELLIPTICAL SEGMENT
C
C** INPUTS
C
C   NPTS -- NUMBER OF INPUTS
C      X -- X STATION
C      A -- HORIZONTAL AXIS AT EACH X STATION
C      B -- VERTICAL AXIS AT EACH X STATION
C
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      DIMENSION TA(100), TB(100), TX(100), XMAJOR(50), XMINOR(50)
      DIMENSION X(NPTS),A(NPTS),B(NPTS),CAYSQ(50),R(2),XL(2),XSTA(50)
      LOGICAL SWITCH
C
C** STORE INPUT PARAMETERS TO BE MANIPULATED
C
      SWITCH=.FALSE.
C
      DO 1000 II=1,NPTS
         IF(A(II) .EQ. B(II))GO TO 1000
         IF(A(II) .LT. B(II))SWITCH=.TRUE.
         GO TO 1010
 1000 CONTINUE
C
 1010 CONTINUE
C
      DO 1020 II=1,NPTS
         IN=II*2-1
         TA(IN)=A(II)
         TB(IN)=B(II)
         IF(SWITCH)TA(IN)=B(II)
         IF(SWITCH)TB(IN)=A(II)
         TX(IN)=X(II)
         TA(IN+1)=-9999.
         TB(IN+1)=-9999.
         TX(IN+1)=-9999.
 1020 CONTINUE
      NPTS2=NPTS*2-1
C
C** LOOK FOR POSSIBLE MAJOR AXIS SHIFT (EX: HORIZ. AXIS TO VERT. AXIS)
C
      DO 1050 J=3,NPTS2,2
         IF(TB(J) .LE. TA(J)) GO TO 1050
C
C** COMPUTE A=B POINT AND PUT IN A DUMMY ARGUMENT (-9999.) LOCATION
C
 1030    SLOPE=(TB(J)-TB(J-2))/(TA(J)-TA(J-2))
         YINT=TB(J)-SLOPE*TA(J)
         XPOS=YINT/(1.-SLOPE)
         TA(J-1)=XPOS
         TB(J-1)=XPOS
         TX(J-1)=TX(J-2)+(TX(J)-TX(J-2))*ABS((TA(J-1)-TA(J-2))/
     1           (TA(J)-TA(J-2)))
C
C** SWITCH REST OF TA & TB PARAMETERS TO REFLECT AXIS SHIFT
C
        DO 1040 K=J,NPTS2,2
           TEMP=TA(K)
           TA(K)=TB(K)
           TB(K)=TEMP
 1040   CONTINUE
 1050 CONTINUE
C
C** REMOVE DUMMY ARRAY ELEMENTS (-9999.)
C
      NN=0
      DO 1060 M=1,NPTS2
         IF(TA(M) .EQ. -9999.) GO TO 1060
         NN=NN+1
         XMAJOR(NN)=TA(M)
         XMINOR(NN)=TB(M)
         XSTA(NN)=TX(M)
 1060 CONTINUE
C
      CAYSQ(1)=0.
      DSWETE=0.0
      IF(XMAJOR(1).NE.0.) CAYSQ(1)=1.-XMINOR(1)**2/XMAJOR(1)**2
      DO 1080 JJ=2,NN
         IF(XMAJOR(JJ).NE.0.) CAYSQ(JJ)=1.-XMINOR(JJ)**2/XMAJOR(JJ)**2
         IF(XMAJOR(JJ).EQ.0.) CAYSQ(JJ)=1.-XMINOR(JJ-1)**2/
     1                                  XMAJOR(JJ-1)**2
         IF(CAYSQ(JJ).EQ.CAYSQ(JJ-1)) GO TO 1070
         XL(1)=XSTA(JJ-1)
         XL(2)=XSTA(JJ)
         IF(XL(1) .EQ. XL(2))GO TO 1080
         R(1)=XMAJOR(JJ-1)
         R(2)=XMAJOR(JJ)
         XCENP=(DXCENP(2,XL,R)-XSTA(JJ-1))/(XSTA(JJ)-XSTA(JJ-1))
         XLMIN=XMINOR(JJ-1)-XMINOR(JJ)
         XLMAJ=XMAJOR(JJ-1)-XMAJOR(JJ)
         CAYSQ(JJ)=1.-(XCENP*XLMIN+XMINOR(JJ))**2/
     1             (XCENP*XLMAJ+XMAJOR(JJ))**2
 1070    E=ELLIP2(CAYSQ(JJ))
         DSWETE=DSWETE+2.*E*SQRT((XMAJOR(JJ)-XMAJOR(JJ-1))**2+
     1          (XSTA(JJ)-XSTA(JJ-1))**2)*
     2          (XMAJOR(JJ)+XMAJOR(JJ-1))
 1080 CONTINUE
      RETURN
      END
