      SUBROUTINE EQN44(GAM,PT,P,AMX)
C
C  COMPUTE MACH NUMBER FROM EQUATION 44 OF NACA 1135
C
C
C  INPUTS
C
C    GAM -- RATIO OF SPECIFIC HEATS FOR THE GAS
C     PT -- TOTAL PRESSURE
C      P -- STATIC PRESSURE
C
C  OUTPUT
C
C    AMX -- MACH NUMBER
C
C  SUBROUTINES CALLED -- NONE
C
      AMX=SQRT(2./(GAM-1.)*((PT/P)**((GAM-1.)/GAM)-1.))
      RETURN
      END
