      SUBROUTINE FCNASB(SWEP50,ASPECT,SECCLA,MACH,CLA)
C
C     THIS SUBROUTINE COMPUTES FIN-ALONE LIFT CURVE SLOPE FOR
C     TWO PANELS CONNECTED AT THE ROOT CHORD.  THE CALCULATION USES
C     THE METHOD OF LOWRY-POLHAMUS (DATCOM 4.1.3.2).  THE LIFT CURVE
C     SLOPE IS BASED ON FIN AREA.
C
C  MODIFIED BY W. BLAKE, WL/FIGC
C
C     INPUTS
C
C       SWEP50 -- HALF CHORD FIN SWEEP ANGLE, DEGREES
C       ASPECT -- EXPOSED ASPECT RATIO OF TWO PANELS
C       SECCLA -- SECTION LIFT COEFFICIENT PER RADIAN
C       MACH   -- FREESTREAM MACH NUMBER
C
C     OUTPUTS
C
C       CLA    -- LIFT CURVE SLOPE REFERENCED TO EXPOSED FIN
C                 AREA, PER DEGREE
C
      COMMON /CONST/PI,RAD,UNUSED,KAND
      REAL MACH,KAPPA
C
C     CALCULATE BETA (MACH SIMILARITY PARAMETER)
C
      BETA=SQRT(1.-MACH**2)
C
C     CALCULATE KAPPA (SECTION LIFT CURVE SLOPE TO TWO PI RATIO)
C
      KAPPA=SECCLA/((2.*PI)/BETA)
C
C     CALCULATE CLA
C
      CLA=2.*PI/(2.+SQRT(((TAN(SWEP50/RAD))**2/BETA**2+1.)*
     *    ASPECT**2*BETA**2/KAPPA**2+4.))*ASPECT/RAD
C
      RETURN
      END
