      FUNCTION FINCEN(SPAN,SWEEP0,CROOT,TAPER)
C
C***  FUNCTION TO COMPUTE THE CENTROID OF AREA FOR A STRAIGHT TAPERED
C***  FIN OR FIN SECTION, MEASURED FROM THE ROOT CHORD LEADING EDGE
C
C***  INPUTS
C
C   SPAN -- PANEL EXPOSED SPAN (TIP-TO-TIP) FOR TWO PANELS
C           JOINED AT THEIR EXPOSED ROOT CHORDS
C SWEEP0 -- PANEL LEADING EDGE SWEEP ANGLE IN DEGREES
C  CROOT -- PANEL EXPOSED ROOT CHORD
C  TAPER -- PANEL TIP CHORD DIVIDED BY EXPOSED ROOT CHORD
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      SIGMA=ASPECT(SPAN,CROOT,TAPER)/4.*(1.+TAPER)*TAN(SWEEP0/RAD)
C
      FINCEN=CROOT/3.*(TAPER+SIGMA+(1.+TAPER*SIGMA)/(1.+TAPER))
C
      RETURN
      END
