      FUNCTION FINPLN(SPAN,CROOT,TAPER)
C
C***  FUNCTION TO COMPUTE THE PLANFORM AREA OF A STRAIGHT TAPERED
C***  FIN OR FIN SEGMENT
C
C***  INPUTS
C
C   SPAN -- PANEL EXPOSED SPAN (TIP-TO-TIP) FOR TWO PANELS
C           JOINED AT THEIR EXPOSED ROOT CHORDS
C  CROOT -- PANEL EXPOSED ROOT CHORD
C  TAPER -- PANEL TIP CHORD DIVIDED BY EXPOSED ROOT CHORD
C
      FINPLN=SPAN/2.*CROOT*(1.+TAPER)
C
      RETURN
      END
