      FUNCTION FIT(A,Y,Z,NROW,NCOL)
C
C***  SOLVE THE POLYNOMIAL EXPANSION OF THE FORM
C***   FIT=A(1)+A(2)*Y+A(3)*Y**2+A(4)*Y**3+A(NCOL)*Y**(NCOL-1)
C***           .   .   .   .   .   .   .   .   .   .   .
C***
C***   +(A(NCOL*(NROW-1)+1)+ ... +A(NCOL*NROW)*Y**(NCOL-1))*Z**(NROW-1)
C
C***  INPUTS
C
C    A -- ARRAY OF TERMS FOR THE POLYNOMIAL EXPANSION
C    Y -- FIRST INDEPENDENT VARIABLE
C    Z -- SECOND INDEPENDENT VARIABLE
C NROW -- NUMBER OF ROWS IN THE EXPANSION (NO LIMIT)
C NCOL -- NUMBER OF COLUMNS IN THE EXPANSION (MAXIMUM IS 8)
C
      DIMENSION A(1),YT(8)
C
      DO 1000 I=2,NCOL
        YT(I)=Y**(I-1)
 1000 CONTINUE
C
      YT(1)=1.
C
      DO 1030 IROW=1,NROW
         NCOUNT=NCOL*(IROW-1)
         S=0.
         DO 1010 ICOL=1,NCOL
            S=S+A(ICOL+NCOUNT)*YT(ICOL)
 1010    CONTINUE
         IF(IROW .EQ. 1)GO TO 1020
         FIT=S*Z**(IROW-1)+FIT
         GO TO 1030
 1020    FIT=S
 1030 CONTINUE
C
      RETURN
      END
