      SUBROUTINE GETETA(FR,MACH,ETA)
C
C***  SUBROUTINE TO COMPUTE THE SUBSONIC CROSS FLOW DRAG
C***  PROPORTIONALITY FACTOR USING GOLDSTEINS RESULTS
C***  AND THE TRANSONIC CORRELATION OF BAKER (AEDC-TR-75-124)
C
C***  INPUT
C
C     FR - OVERAL BODY FINENESS RATIO, LENGTH/DIAMETER
C   MACH - FREE STREAM MACH NUMBER
C
C***  OUTPUT
C
C    ETA - CROSS FLOW DRAG PROPORTIONALITY FACTOR
C
      DIMENSION AETA(9),ALD(9)
C
      REAL MACH
C
      DATA ALD/ 1.,2.,4.,6.,8.,12.,20.,30.,40. /
      DATA AETA/.530,.570,.613,.640,.665,.700,.765,.798,.820/
C
      ETA=1.0
      IF(MACH .GT. 1.4)GO TO 1030
C
C***  LINEARILY INTERPOLATE/EXTRAPOLATE
C
      CALL LNTRP(ALD,AETA,9,FR,ETA)
      IF(ETA .GT. 1.)ETA=1.
C
C     * IF MACH LIES BETWEEN 0.6 AND 1.4
           IF(MACH .GT. 0.6 .AND. MACH .LT. 1.4)GO TO 1000
           GO TO 1010
C     * THEN USE BAKERS TRANSONIC FAIRING
 1000      ETA=ETA+(1.-ETA)/2.*(1.+TANH((MACH-1.)*(15./MACH**4)))
           GO TO 1020
C     * ELSE CONTINUE
 1010      CONTINUE
 1020      CONTINUE
C     * ENDIF
C
 1030 CONTINUE
C
      RETURN
      END
