      SUBROUTINE HEADR9
C
C***  FORTRAN 90 VERSION
C***  SUBROUTINE TO WRITE THE CASE HEADER ON DEMAND
C
      COMMON /CASEID/ IDCASE(74),KOUNT,NAMSV(100),CASE,NOEXTR,NOLAT,IR,
     1                IPAGE
C
      CHARACTER*4 IBLANK,IDCASE,ICASE
C
      INTEGER CASE
      DIMENSION ICASE(136)
      DATA IBLANK /'    '/
C
      IF(CASE .LE. 0)WRITE(6,1060)
      IF(CASE .LE. 0)GO TO 1040
C
      IPAGE=IPAGE+1
      WRITE(6,1050)CASE,IPAGE
C
C***   DETERMINE THE LENGTH OF THE IDENTIFICATION
C
      DO 1000 I=1,72
         II=72-I+1
         ICOUNT=II
         IF(IDCASE(II) .NE. IBLANK)GO TO 1010
 1000 CONTINUE
      IF(ICOUNT .EQ. 1)GO TO 1040
 1010 CONTINUE
C
C***   NOW CENTER CASE ID ON PAGE
C
      ISKIP=(72-ICOUNT)/2-2
C
C***   FILL BUFFER WITH BLANKS
C
      DO 1020 I=1,72
         ICASE(I)=IBLANK
 1020 CONTINUE
C
C***   FILL BUFFER WITH CASE ID
C
      DO 1030 I=1,ICOUNT
         JJ=I+ISKIP
         ICASE(JJ)=IDCASE(I)
 1030 CONTINUE
      WRITE(6,1070)(ICASE(I),I=1,72)
C
 1040 CONTINUE
C
 1050 FORMAT('1',8X,
     1    ' ***** THE USAF AUTOMATED MISSILE DATCOM * REV 3/99 *****',
     2    '     CASE',I4,/,
     3 9X,'      AERODYNAMIC METHODS FOR MISSILE CONFIGURATIONS     ',
     4    '     PAGE',I4)
 1060 FORMAT('1',8X,
     1    ' ***** THE USAF AUTOMATED MISSILE DATCOM * REV 3/99 *****',/,
     3 9X,'      AERODYNAMIC METHODS FOR MISSILE CONFIGURATIONS     ')
 1070 FORMAT(4X,72A1)
C
      RETURN
      END
