      SUBROUTINE ILTFR
C
C     THIS SUBROUTINE DETERMINES THE MAXIMUM EQUIVALENT DIAMETER
C     OF THE INLET, DIVERTER, AND BODY THEN COMPUTES THE FINENESS RATIO
C     OF EACH COMPONENT.
C
C  WRITTEN BY M. MOORE, MCDONNELL DOUGLAS
C
C                  *********************
C                  * INPUT/OUTPUT LIST *
C                  *********************
C
C
C     ***** INPUTS *****          ***** OUTPUTS *****
C
C           DEQD                       FRI
C           XI                         FRD
C           XD                         FRB
C           LBOD
C           RBOD
C
C     SUBROUTINES USED: NONE
C
C
      COMMON /INLETN/ NIN,INTYPE,XINLT,XDIV,HDIV,LDIV,PHI(20),
     1                XI(5),HI(5),WI(5),ICOVER,RAMANG,IAD,MFR(20)
      COMMON /ILTGEO/ LENGTH(5),LLNGTH(5),ALPEFF(5),SI(5),
     1                CRXLEN(5),DEQI(5),XMIDI(5),XMIDD(3),
     2                XD(3),HD(3),WD(3),DEQD(3),
     3                RARC(5),DLEN(3),KWA(20),KWB(20),
     4                RA2(20),RB2(20),AREAI(5),AREAD(3)
      COMMON /FLC/    NALPHA,ALPHA(20),BETA,PHIROL,NMACH,MACH(20),
     1                ALT(20),REN(20),FLDUM(60)
      COMMON /REFQN/  SREF,LREF,BREF,ROUGH,XCG,ZCG,SCALE,BLAYER,RHR
      COMMON /CONST/  PI,RAD,UNUSED,KAND
      COMMON /POTENT/ CNP(20),CYP(20),CMP(20),CLNP(20)
      COMMON / MOMEN/ CNMOM(20),CYMOM(20)
      COMMON /LINEAR/ ARA,ARB,CNLIN(20),CMLIN(20),
     1                CYLIN(20),CLNLIN(20)
      COMMON /CFFLOW/ CNCF(20),CYCF(20),
     1                CMCF(20),CLNCF(20)
      COMMON /ILTVSC/ THETAI(5,20),PHIR(20),CRXIWD(5,20),
     1                CRXIHT(5,20),CNNIZP(5,20),
     2                CNNIZN(5,20),CNNIYP(5,20),
     3                CNNIYN(5,20),PANILN(5,5,20),
     4                CNCIRN,FRI,RARX(3),
     5                DLCNAP(3,20),DLCNAN(3,20),
     6                DLCYAP(3,20),DLCYAN(3,20)
      COMMON /DIVVSC/ THETAD(5,20),CRXDWD(3,20),
     1                CRXDHT(3,20),CNNDZP(3,20),
     2                CNNDZN(3,20),CNNDYP(3,20),
     3                CNNDYN(3,20),PANDLN(5,20),FRD
      COMMON /BODVSC/ DLCNBP(5,20),DLCNBN(5,20),
     1                DLCYBP(5,20),DLCYBN(5,20),FRB
C
      REAL NIN,INTYPE,LENGTH,LLNGTH,LREF,LDIV,MACH,KWA,KWB
      REAL NALPHA,NMACH
      LOGICAL ICOVER
      COMMON /GEOBOD/ DUM(32),DMAX,SMAX,LBOD,GDUM(12)
      REAL LBOD
      RBOD=DMAX/2.0
C
C     SET INITIAL MAXIMUM EQUIVALENT DIAMETER
      DEQM = 0.0
      DEQN = 0.0
C
C     LOOP FOR EACH CROSS SECTION OF THE INLET
      DO 100 ICRX = 1, 5
C
C        CHECK IF NEW MAXIMUM EQUIVALENT DIAMETER
         IF (DEQI(ICRX) .GT. DEQM) DEQM = DEQI(ICRX)
C
  100 CONTINUE
C
C     LOOP FOR EACH CROSS SECTION OF THE DIVERTER
      DO 110 IDCRX = 1, 3
C
C        CHECK IF NEW MAXIMUM EQUIVALENT DIAMETER
         IF (DEQD(IDCRX) .GT. DEQN) DEQN = DEQD(IDCRX)
C
  110 CONTINUE
C
C     COMPUTE THE BODY FINENESS RATIOS
      FRI = ABS((XI(5) - XI(1))) / DEQM
      IF(HDIV .GT. 0.0)THEN
        FRD = ABS((XD(3) - XD(1))) / DEQN
      ELSE
        FRD = 0.0
      ENDIF
      FRB = ABS(LBOD) / (2.* RBOD)
C
      RETURN
      END
