      SUBROUTINE INLETA(IM,CAADD,MFRM)
C
C*** PRINT INLET AERODYANMIC INCREMENTALS
C
C  WRITTEN BY M. MOORE, MCDONNELL DOUGLAS
C
      COMMON /INLETN/ NIN,INTYPE,XINLT,XDIV,HDIV,LDIV,PHI(20),
     1            XI(5),HI(5),WI(5),ICOVER,RAMANG,IADD,MFR(20)
      COMMON /INLTD/ CNI(20),CMI(20),CAI(20),CYI(20),CLNI(20),
     1               CLLI(20)
      COMMON /FLC/ NALPHA,ALPHA(20),BETA,PHIROL,NMACH,MACH(20),
     1             FLDUM(100)
      REAL NALPHA,NMACH,MACH,MFR,MFRM,NIN,INTYPE,LDIV
      LOGICAL NA,NN,NM,ICOVER,IADD
C
      NALP=NALPHA+.5
C
      CALL HEADR9
      WRITE(6,1000)
      CALL PRFLC9(IM,NA,NN,NM)
C
      WRITE (6,1050)
      IF (IADD.AND.(.NOT.ICOVER).AND.(MACH(IM).GE.1.0)) THEN
        DO 200 I=1,NALP
          WRITE(6,1060) ALPHA(I),CNI(I),CMI(I),CAI(I),
     &                  CAADD,CYI(I),CLNI(I),CLLI(I)
  200   CONTINUE
        WRITE(6,1070) MFR(IM),MFRM
      ELSE
        DO 100 I=1,NALP
          WRITE(6,1020) ALPHA(I),CNI(I),CMI(I),CAI(I),
     1              CYI(I),CLNI(I),CLLI(I)
  100   CONTINUE
      ENDIF
      IF (IADD.AND.ICOVER) WRITE(6,1030)
      IF (IADD.AND.(MACH(IM).LT.1.0)) WRITE(6,1040)
C
 1000 FORMAT(23X,'INLET AERODYNAMIC INCREMENTALS',/)
 1020 FORMAT(4X,F7.2,3(F9.4),9X,3(F9.4))
 1030 FORMAT(/,4X,'ADDITIVE DRAG CANNOT BE CALCULATED BECAUSE',
     &       ' INLET IS COVERED')
 1040 FORMAT(/,4X,'ADDITIVE DRAG CANNOT BE CALCULATED BECAUSE',
     &       ' MACH NUMBER IS LESS THAN 1.0')
 1050 FORMAT(6X,'ALPHA',2X,'CN-INLT',2X,'CM-INLT',2X,'CA-INLT',
     1       3X,'CA-ADD',2X,'CY-INLT',2X,'CLN-INLT',1X,'CLL-INLT')
 1060 FORMAT(4X,F7.2,7(F9.4))
 1070 FORMAT(/,4X,'NOTE: CA-ADD IS INLET ADDITIVE DRAG COEFFICIENT',
     &       ' FOR MASS FLOW RATIO OF ',F4.2,/,4X,
     &       'NOTE: MAXIMUM MASS FLOW RATIO ',
     &       'AT THESE FLIGHT CONDITIONS IS ',F4.2)
C
      RETURN
      END
