      SUBROUTINE INSBLK(KOL,ICOL,ISKP)
C
C***  ROUTINE TO INSERT A BLANK COLUMN IN THE CARD IMAGE AT ICOL
C***  THE REMAINDER OF THE CARD IS SHIFTED TO THE RIGHT
C
C  INPUTS
C
C    KOL -- 80 COLUMN CARD IMAGE
C   ICOL -- COLUMN WHERE BLANK IS TO BE INSERTED
C
C  OUTPUT
C
C   ISKP -- SET TO 1 IF COLUMN 80 IS NOT BLANK
C           WAS SUCCESSFUL IF EQUALS TO 0
C
      CHARACTER*4 IBLANK,KOL,IBUFF
      DIMENSION KOL(80),IBUFF(80)
C
      DATA IBLANK /'    ' /
C
      ISKP=1
C
C***  SKIP IF COLUMN 80 IS NOT BLANK
C
      IF(KOL(80) .NE. IBLANK)GO TO 1030
C
      ICOLM1=ICOL-1
C
C***  RETAIN FIRST ICOL COLUMNS IN BUFFER
C
      DO 1000 I=1,ICOLM1
         IBUFF(I)=KOL(I)
 1000 CONTINUE
C
C***  INSERT BLANK
C
      IBUFF(ICOL)=IBLANK
C
C***  GET THE REST OF THE CARD INTO THE BUFFER
C
      DO 1010 I=ICOL,79
         IBUFF(I+1)=KOL(I)
 1010 CONTINUE
C
C***  WRITE BUFFER OVER PREVIOUS CARD IMAGE
C
      DO 1020 I=1,80
         KOL(I)=IBUFF(I)
 1020 CONTINUE
C
      ISKP=0
C
 1030 CONTINUE
C
      RETURN
      END
