      SUBROUTINE INZBOD
C
C***  INITIALIZE ALL BODY ARRAYS
C
C***  BODY AND INLET INPUTS
C
      COMMON /ABODIN/ NX,XO,X(50),R(50),TNOSE,LNOSE,DNOSE,BNOSE,
     1                TRUNC,LCENTR,DCENTR,TAFT,LAFT,DAFT,
     2                POWER,DISCON(20),ELLIP(50),H(50),
     3                ENOSE,ECENTR,EAFT,DEXIT,BASE,BETAN,
     4                JMACH(20),PRAT(20),TRAT(20),PROTUB,
     5                NPROT,PTYPE(20),XPROT(20),NLOC(20),
     6                BLDMEM(20),BLDTYP(100),LPROT(100),
     7                WPROT(100),HPROT(100),OPROT(100)
C
      REAL NX,LNOSE,LCENTR,LAFT,JMACH,NPROT,NLOC,LPROT
C
      LOGICAL TRUNC,BASE,PROTUB
C
      COMMON /INLETN/ RINLET(41),ICOVER,RAMANG,IADD,MFR(20)
      LOGICAL ICOVER,IADD
      REAL MFR
      COMMON /INLTD/  DINLET(120)
C
C***  BODY GEOMETRIC CONSTANTS
C
      COMMON /GEOBOD/ GEOB(47)
C
C***  PROGRAM CONSTANTS
C
      COMMON /CONST/  PI,RAD,UNUSED,KAND
C
      COMMON /PAERO/ PDATA(4024)
C
C****   INITIALIZE PARTIAL AERO COEFFICIENTS   *******
      DO 10 I=1,4024
         PDATA(I)=UNUSED
  10  CONTINUE
C
C****   INITIALIZE AXIBOD OR ELLBOD INPUTS  *******
      NX=UNUSED
      TNOSE=UNUSED
      LNOSE=UNUSED
      DNOSE=UNUSED
      BNOSE=UNUSED
      TRUNC=.FALSE.
      LCENTR=UNUSED
      DCENTR=UNUSED
      TAFT=UNUSED
      LAFT=UNUSED
      DAFT=UNUSED
      POWER=UNUSED
      XO=UNUSED
      DO 20 I=1,50
        X(I)=UNUSED
        R(I)=UNUSED
        IF(I .LE. 20) DISCON(I)=UNUSED
 20   CONTINUE
C
C*****   INITIALIZE BASE-JET PLUME INTERACTION INPUTS   *******
      BASE=.FALSE.
      BETAN=UNUSED
      DO 30 I=1,20
        JMACH(I)=UNUSED
        PRAT(I)=UNUSED
        TRAT(I)=UNUSED
 30   CONTINUE
C
C***    INITIALIZE BODY GEOMETRIC CONSTANTS  *******
      DO 40 I=1,47
         GEOB(I)=UNUSED
 40   CONTINUE
C
C****   INITIALIZE ELLIPTICAL BODY INPUTS  *******
      DO 50 I=1,50
         ELLIP(I)=UNUSED
         H(I)=UNUSED
 50   CONTINUE
      ENOSE=UNUSED
      ECENTR=UNUSED
      EAFT=UNUSED
      DEXIT=UNUSED
C
C***   INITIALIZE PROTUBERANCE INPUTS  *******
      PROTUB=.FALSE.
      NPROT=0.0
      DO 60 I=1,20
        PTYPE(I)=UNUSED
        XPROT(I)=UNUSED
        NLOC(I)=0.0
        BLDMEM(I)=0.0
 60   CONTINUE
      DO 70 I=1,100
        BLDTYP(I)=UNUSED
        LPROT(I)=UNUSED
        WPROT(I)=UNUSED
        HPROT(I)=UNUSED
        OPROT(I)=0.0
 70   CONTINUE
C
C***   INITIALIZE INLET INPUTS   ******        
      DO 80 I=1,41
         RINLET(I)=UNUSED
 80   CONTINUE
      ICOVER=.FALSE.
      IADD=.FALSE.
      DO 90 I=1,20
        MFR(I)=UNUSED
 90   CONTINUE
      RAMANG=UNUSED
      DO 100 I=1,100
         DINLET(I)=UNUSED
 100  CONTINUE
C
      RETURN
      END
