      SUBROUTINE INZREF
C
C***  INITIALIZE ALL REFERENCE QUANTITIES
C
C***  REFERENCE QUANTITY INPUTS
C
      COMMON /REFQN/  SREF,LREF,LATREF,ROUGH,XCG,ZCG,SCALE,BLAYER,RHR
C
      REAL LREF,LATREF
C
C***  PROGRAM CONSTANTS
C
      COMMON /CONST/  PI,RAD,UNUSED,KAND
C
      SREF=UNUSED
      LREF=UNUSED
      LATREF=UNUSED
      ROUGH=UNUSED
      XCG=UNUSED
      ZCG=UNUSED
      SCALE=UNUSED
      BLAYER=UNUSED
      RHR=UNUSED
C
      RETURN
      END
