      SUBROUTINE LOOP(I,IMAX,FLAG)
C
C***  THIS ROUTINE INCREMENTS THE LOOP INDEX AND SETS THE LOOP FLAG
C***  FOR A LOOP WHICH HAS A BRANCH OUTSIDE OF THE RANGE OF THE LOOP
C
C***  INPUT PARAMETERS
C       I=CURRENT VALUE OF LOOP INDEX
C       IMAX=UPPER LIMIT OF LOOP INDEX
C
C***  OUTPUT VARIABLES
C       I=UPDATED LOOP INDEX, I=I+1
C       FLAG=.TRUE. IF ( I.LE.IMAX)
C
      LOGICAL FLAG
      I=I+1
      IF(I.LE.IMAX) GO TO 1000
        FLAG=.FALSE.
        GO TO 1010
C
 1000   FLAG=.TRUE.
 1010 CONTINUE
      RETURN
      END
