      SUBROUTINE LUGSHO(MACH,DEL,K,NM,HPROT,WPROT,LPROT,OPROT,CDLAUN)
C
C  WRITTEN BY K. DETERS, MCDONNELL DOUGLAS
C
      REAL MACH,HPROT(100),WPROT(100),LPROT(100),OPROT(100)
      CDTOT=0.0
      DO 10 I=1,NM
      K=K+1
      IF (HPROT(K) .LT. .0001 .OR. WPROT(K) .LT. .0001) GOTO 10
      CALL FLAT(MACH,DEL,HPROT(K),WPROT(K),LPROT(K),OPROT(K),CDSUM)
      CDTOT=CDTOT+CDSUM
 10   CONTINUE
      CDLAUN=CDTOT
      RETURN
      END

