      SUBROUTINE MATCHX(J,RN,B,DELM,XL,PST,PL,X,P,XST)
C
C  COMPUTE THE X MATCHING POINT FOR A SPHERICAL NOSE CAP
C
C  INPUTS
C      J -- INTEGER STATION NUMBER (1=NOSE)
C     RN -- NOSE RADIUS
C      B -- NOSE BLUNTNESS FACTOR
C   DELM -- MAXIMUM DEFLECTION ANGLE TO SUPPORT A SHOCK (RADIANS)
C     XL -- X POSITION ON FIRST FRUSTRUM
C    PST -- STATIC PRESSURE
C     PL -- LOCAL PRESSURE
C      X -- X STATION
C      P -- PRESSURE
C
C  OUTPUT
C
C    XST -- X STATION FOR MATCHING
C
C  SUBROUTINES CALLED -- NONE
C
C  MATCH POINT ON SPHERICAL CAP
C
      IF(J.EQ.1)XST=-RN/B*(1.-SQRT(1.-1./(1.-TAN(DELM)**2/B)))
C
C  MATCH POINT ON BODY FRUSTRUMS
C
      IF(J.NE.1)XST=XL+(PST-PL)*(X-XL)/(P-PL)
      RETURN
      END
