      SUBROUTINE PRIAXI(ITYPE)
C
C***  SUBROUTINE TO PRINT THE AXISYMMETRIC BODY GEOMETRY DATA
C
      DIMENSION ICONE(2),IOGIV(2),IPOWR(2),IHACK(2),IKARM(2)
      DIMENSION KAST(50),ICYL(2)
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      COMMON /LOGIC/ LFLAGS(18),LDIMIN,LDIMFT,LDIMCM,LDIMM,LDUM2(6)
      LOGICAL        LFLAGS    ,LDIMIN,LDIMFT,LDIMCM,LDIMM
      LOGICAL ASTFLG
C
C
      COMMON /GEOBOD/ SPNOSE,SWNOSE,VOLNOS,XCVNOS,XCPNOS,FRNOSE,
     1  THEOLN,THEOFN,SPCENT,SWCENT,VOLCEN,XCVCEN,XCPCEN,FRCENT,
     2  THEOLC,THEOFC,SPAFT ,SWAFT ,VOLAFT,XCVAFT,XCPAFT,FRAFT ,
     3  THEOLA,THEOFA,SPLAN ,SWET  ,VOL   ,XCENTV,XCENTP,FR    ,
     4                DBASE ,SBASE ,DMAX  ,SMAX  ,LTOTAL,GDUM(12)
C
      COMMON /ABODIN/ NX,XO,X(50),R(50),TNOSE,LNOSE,DNOSE,BNOSE,
     1                TRUNC,LCENTR,DCENTR,TAFT,LAFT,DAFT,
     2                POWER,DISCON(20),ADUM(748)
      REAL NX,LNOSE,LCENTR,LAFT,LTOTAL
C
      CHARACTER*4 IDASH,ICONE,ICYL,IOGIV,IPOWR,IHACK,IKARM,
     1  IUNIT1,IUNIT2,IUNIT3,IUNIT4,IBLANK,IAST,KAND,
     2  NAM1,NAM2,NAM3,NAM4,NAM5,NAM6,IAXIS,KAST
C
      LOGICAL TRUNC
C
      DATA IDASH/'----'/
      DATA ICONE/'   C','ONIC'/
      DATA ICYL /'CYLI','NDER'/
      DATA IOGIV/'   O','GIVE'/
      DATA IPOWR/'   P','OWER'/
      DATA IHACK/'LV-H','AACK'/
      DATA IKARM/'VONK','ARMN'/
C
      DATA IUNIT1/'  IN'/
      DATA IUNIT2/'  FT'/
      DATA IUNIT3/'  CM'/
      DATA IUNIT4/'   M'/
      DATA IBLANK/'    '/
      DATA IAST  /'*   '/
      ASTFLG=.FALSE.
C
      NNX=NX+0.5
C
      NAM1=IDASH
      NAM2=IDASH
      NAM3=IDASH
      NAM4=IDASH
      NAM5=IDASH
      NAM6=IDASH
C
      IF(LNOSE .GT. UNUSED .AND. TNOSE .EQ. 0.)NAM1=ICONE(1)
      IF(LNOSE .GT. UNUSED .AND. TNOSE .EQ. 0.)NAM2=ICONE(2)
      IF(LNOSE .GT. UNUSED .AND. TNOSE .EQ. 1.)NAM1=IOGIV(1)
      IF(LNOSE .GT. UNUSED .AND. TNOSE .EQ. 1.)NAM2=IOGIV(2)
      IF(LNOSE .GT. UNUSED .AND. TNOSE .EQ. 2.)NAM1=IPOWR(1)
      IF(LNOSE .GT. UNUSED .AND. TNOSE .EQ. 2.)NAM2=IPOWR(2)
      IF(LNOSE .GT. UNUSED .AND. TNOSE .EQ. 3.)NAM1=IHACK(1)
      IF(LNOSE .GT. UNUSED .AND. TNOSE .EQ. 3.)NAM2=IHACK(2)
      IF(LNOSE .GT. UNUSED .AND. TNOSE .EQ. 4.)NAM1=IKARM(1)
      IF(LNOSE .GT. UNUSED .AND. TNOSE .EQ. 4.)NAM2=IKARM(2)
      IF(LCENTR .GT. UNUSED)NAM3=ICONE(1)
      IF(LCENTR .GT. UNUSED)NAM4=ICONE(2)
      IF(LCENTR .GT. UNUSED .AND. DNOSE.EQ.DCENTR)NAM3=ICYL(1)
      IF(LCENTR .GT. UNUSED .AND. DNOSE.EQ.DCENTR)NAM4=ICYL(2)
      IF(LAFT .GT. UNUSED .AND. TAFT .EQ. 0.)NAM5=ICONE(1)
      IF(LAFT .GT. UNUSED .AND. TAFT .EQ. 0.)NAM6=ICONE(2)
      IF(LAFT .GT. UNUSED .AND. TAFT .EQ. 1.)NAM5=IOGIV(1)
      IF(LAFT .GT. UNUSED .AND. TAFT .EQ. 1.)NAM6=IOGIV(2)
C
      CALL HEADR9
C
      WRITE(6,1050)
      IF(ITYPE .EQ. 2)WRITE(6,1060)
C
      IAXIS=IUNIT2
      IF(LDIMIN)IAXIS=IUNIT1
      IF(LDIMCM)IAXIS=IUNIT3
      IF(LDIMM)IAXIS=IUNIT4
C
C  TYPE 2 INPUTS
C
      IF(ITYPE .EQ. 1)GO TO 1010
C
      WRITE(6,1070)NAM1,NAM2,NAM3,NAM4,NAM5,NAM6
      WRITE(6,1080)LNOSE,LCENTR,LAFT,LTOTAL,IAXIS
      WRITE(6,1090)FRNOSE,FRCENT,FRAFT,FR
      WRITE(6,1100)SPNOSE,SPCENT,SPAFT,SPLAN,IAXIS
      WRITE(6,1110)XCPNOS,XCPCEN,XCPAFT,XCENTP,IAXIS
      WRITE(6,1120)SWNOSE,SWCENT,SWAFT,SWET,IAXIS
      WRITE(6,1130)VOLNOS,VOLCEN,VOLAFT,VOL,IAXIS
      WRITE(6,1140)XCVNOS,XCVCEN,XCVAFT,XCENTV,IAXIS
      GO TO 1020
C
C  TYPE 1 INPUTS
C
 1010 CONTINUE
      WRITE(6,1180)LTOTAL,FR,SPLAN,XCENTP,SWET,VOL,XCENTV,IAXIS
C
 1020 CONTINUE
C
      IF(LNOSE .GT. UNUSED)BRATIO=BNOSE/(DNOSE/2.)
      IF(LNOSE .GT. UNUSED .AND. .NOT.TRUNC .AND. BNOSE .GT. UNUSED)
     1  WRITE(6,1200)BRATIO
C
      WRITE(6,1150)
C
C  IDENTIFY DISCONTINUOUS POINTS
C
      DO 1030 I=1,NNX
         IF(R(I) .LE. UNUSED)R(I)=0.
         KAST(I)=IBLANK
 1030 CONTINUE
C
      DO 1040 I=1,20
         IF(DISCON(I) .EQ. UNUSED)GO TO 1040
         ASTFLG=.TRUE.
         JJ=DISCON(I)+0.5
         KAST(JJ)=IAST
 1040 CONTINUE
C
      WRITE(6,1160)(X(I),KAST(I),I=1,NNX)
      WRITE(6,1170)(R(I),KAST(I),I=1,NNX)
      IF(ASTFLG)WRITE(6,1190)
C
 1050 FORMAT(24X,'AXISYMMETRIC BODY DEFINITION',/)
 1060 FORMAT(29X,'NOSE',3X,'CENTERBODY',5X,
     1 'AFT BODY',8X,'TOTAL')
 1070 FORMAT(4X,'SHAPE           ',5X,2A4,5X,2A4,5X,2A4)
 1080 FORMAT(4X,'LENGTH          ',4F13.3,A4)
 1090 FORMAT(4X,'FINENESS RATIO  ',4F13.3)
 1100 FORMAT(4X,'PLANFORM AREA   ',4F13.3,A4,'**2')
 1110 FORMAT(4X,'AREA CENTROID   ',4F13.3,A4)
 1120 FORMAT(4X,'WETTED AREA     ',4F13.3,A4,'**2')
 1130 FORMAT(4X,'VOLUME          ',4F13.3,A4,'**3')
 1140 FORMAT(4X,'VOL. CENTROID   ',4F13.3,A4,/)
C
 1150 FORMAT(30X,'MOLD LINE CONTOUR',/)
 1160 FORMAT(4X,' LONGITUDINAL STATIONS',5(F10.4,A1),/,4X,
     1  7(F10.4,A1),/,4X,7(F10.4,A1),/,4X,7(F10.4,A1),/,
     2  4X,7(F10.4,A1),/,4X,7(F10.4,A1),/,4X,7(F10.4,A1),
     3  /,4X,3(F10.4,A1))
 1170 FORMAT(/,4X,'            BODY RADII',5(F10.4,A1),/,4X,
     1  7(F10.4,A1),/,4X,7(F10.4,A1),/,4X,7(F10.4,A1),/,
     2  4X,7(F10.4,A1),/,4X,7(F10.4,A1),/,4X,7(F10.4,A1),
     3  /,4X,3(F10.4,A1))
 1180 FORMAT(4X,'LENGTH         ',F13.4,
     1       4X,'FINENESS RATIO ',F13.4,
     2       4X,'PLANFORM AREA  ',F13.4,
     3       4X,'AREA CENTROID  ',F13.4,
     4       4X,'WETTED AREA    ',F13.4,
     5       4X,'VOLUME         ',F13.4,
     6       4X,'VOLUME CENTROID',F13.4,'UNITS ARE IN',A4,/)
 1190 FORMAT(4X,'NOTE - * INDICATES SLOPE DISCONTINUOUS POINTS')
 1200 FORMAT(4X,'NOSE IS SPHERICALLY BLUNTED, BLUNTNESS RATIO =',F6.4)
      RETURN
      END
