      SUBROUTINE SIMPW(CP, DZDX, DX, NI, NF, DCA)
C
C      SIMPSONS RULE INTEGRATION OF CP*DZDX, SUM INTO DCA
C
C      INPUT VARIABLES
C          CP - PRESSURE COEFFICIENT
C        DZDX - SURFACE SLOPE
C          DX - DISTANCE BETWEEN POINTS
C          NI - INITIAL POINT IN CP ARRAY
C          NF - FINAL POINT IN CP ARRAY
C
C      OUTPUT VARIABLE
C         DCA - INCREMENTAL AXIAL FORCE, INTEGRATION OF CP*DZDX
C
      DIMENSION CP(60), DZDX(60)
C
      F1 = CP(NI)*DZDX(NI)
      N1 = NI+1
      DO 10 I=N1,NF,2
        F2  = CP(I)*DZDX(I)
        F3  = 0.
        IF((I+1) .LE. NF)F3  = CP(I+1)*DZDX(I+1)
        DCA = DCA+DX*(F1+4.0*F2+F3)/3.0
        F1  = F3
   10 CONTINUE
C
      RETURN
      END
