      SUBROUTINE SPHERE(AA,NX,X,R,DIAM)
C
C***  CALCULATE THE CHARACTERISTICS OF A SPHERICAL NOSE CAP
C
C***  INPUTS
C
C     NX -- NUMBER OF INPUT POINTS
C      X -- X COORDINATES
C      R -- RADII AT EACH X STATION
C   DIAM -- DIAMETER OF SPHERE
C
C***  OUTPUT
C
C     AA -- ARRAY OF CHARACTERISTICS TO BE COMPUTED
C           AA(1)=PLANFORM AREA
C           AA(2)=WETTED AREA
C           AA(3)=VOLUME
C           AA(4)=VOLUME CENTROID
C           AA(5)=PLANFORM CENTROID
C           AA(6)=FINENESS RATIO
C           AA(7)=THEORETICAL LENGTH
C           AA(8)=THEORETICAL FINENESS RATIO
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      DIMENSION X(50),R(50),AA(8)
C
      REAL NX
C
      NPTS=11
C
      FR=0.5
      THEOL=DIAM/2.
      FF=0.5
C
      SP=0.5*PI*DIAM**2/4.
C
      SW=0.5*PI*DIAM**2
C
      VOL=0.5*PI*DIAM**3/6.
C
      XCENV=DIAM/2.-3.*DIAM/16.
C
      XCENP=DIAM/2.-4.*(DIAM/2.)/(3.*PI)
C
      DO 1000 I=1,NPTS
         X(I)=FLOAT(I-1)*DIAM/(2.*FLOAT(NPTS-1))
         R(I)=SQRT((DIAM/2.)**2-(X(I)-DIAM/2.)**2)
 1000 CONTINUE
C
      NX=NX+FLOAT(NPTS)
C
      AA(1)=SP
      AA(2)=SW
      AA(3)=VOL
      AA(4)=XCENV
      AA(5)=XCENP
      AA(6)=FR
      AA(7)=THEOL
      AA(8)=FF
C
      RETURN
      END
