      SUBROUTINE STBODY(IM)
C
C***  SUBROUTINE TO COMPUTE THE SUBSONIC AND TRANSONIC
C***  CHARACTERISTICS OF AXISYMMETRIC BODIES
C
C***  COMPUTE NORMAL FORCE
C
      CALL BODYCN(IM,CNAN,CNAC,CNABT)
C
C***  COMPUTE AXIAL FORCE
C
      CALL BODYCA(IM)
C
C***  COMPUTE PITCHING MOMENT
C
      CALL BODYCM(IM,CNAN,CNAC,CNABT)
C
      RETURN
      END
