      FUNCTION SWEEPN(STAM,SWEEPM,STAN,SPAN,CROOT,TAPER)
C
C***  FUNCTION TO COMPUTE THE SWEEP ANGLE OF A STRAIGHT TAPERED FIN
C***  OR FIN SECTION AT STATION N (STAN) WHEN THE SWEEP AT STATION M
C***  (STAM) IS KNOWN
C
C***  INPUTS
C
C   STAM -- PANEL CHORD STATION OF KNOWN SWEEP
C           (0.0 IS THE LEADING EDGE AND 1.0 IS THE TRAILING EDGE)
C SWEEPM -- SWEEP ANGLE (IN DEGREES) AT STATION M
C   STAN -- PANEL CHORD STATION WHERE SWEEP ANGLE IS DESIRED
C   SPAN -- PANEL EXPOSED SPAN (TIP-TO-TIP) FOR TWO PANELS
C           JOINED AT THEIR EXPOSED ROOT CHORDS
C  CROOT -- PANEL EXPOSED ROOT CHORD
C  TAPER -- PANEL TIP CHORD DIVIDED BY EXPOSED ROOT CHORD
C
      COMMON /CONST/ PI,RAD,UNUSED,KAND
C
      TANN=TAN(SWEEPM/RAD)-4./ASPECT(SPAN,CROOT,TAPER)*
     1     (STAN-STAM)*(1.-TAPER)/(1.+TAPER)
C
      SWEEPN=ATAN(TANN)*RAD
C
      RETURN
      END
